-- Level 3: depend on MISSION_ASSIGNMENTS
DROP TABLE IF EXISTS ASSIGNMENT_SENSORS;
DROP TABLE IF EXISTS FLIGHT_ALERTS;

-- Level 2: depend on OPERATORS + DRONES + MISSIONS
DROP TABLE IF EXISTS MISSION_ASSIGNMENTS;

-- Level 2: depends on DRONES
DROP TABLE IF EXISTS MAINTENANCE_LOGS;

-- Level 2: depends on DRONE_MODELS + OPERATORS
DROP TABLE IF EXISTS OPERATOR_CERTIFICATIONS;

-- Level 2: depends on SENSORS + DRONE_MODELS
DROP TABLE IF EXISTS FITS;

-- Level 1: depends on CLIENTS
DROP TABLE IF EXISTS MISSIONS;

-- Level 1: depends on DRONE_MODELS
DROP TABLE IF EXISTS DRONES;

-- Level 0: no foreign keys
DROP TABLE IF EXISTS SENSORS;
DROP TABLE IF EXISTS OPERATORS;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS DRONE_MODELS;