insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (101, 'Gallardo Mk.101', 'Wuckert-Armstrong', 23.36, 8);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (102, 'Element Mk.102', 'Ferry-Walsh', 18.02, 56);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (103, 'Savana 1500 Mk.103', 'Ferry-Skiles', 20.73, 81);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (104, 'Sportage Mk.104', 'Stracke and Sons', 16.41, 45);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (105, 'Dakota Mk.105', 'Gorczany Group', 1.82, 2);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (106, 'Ram 1500 Club Mk.106', 'Anderson LLC', 37.62, 118);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (107, 'Tribeca Mk.107', 'Jones, Hansen and O''Hara', 21.02, 115);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (108, 'RS 4 Mk.108', 'Witting and Sons', 29.96, 42);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (109, 'XK Series Mk.109', 'O''Connell-Simonis', 47.78, 42);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (110, 'Jimmy Mk.110', 'Stracke Inc', 16.49, 55);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (111, 'SL-Class Mk.111', 'Hegmann-Hettinger', 9.73, 43);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (112, 'Ram Wagon B250 Mk.112', 'Klocko and Sons', 15.24, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (113, 'Tracer Mk.113', 'Runolfsson, Osinski and Huel', 3.16, 21);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (114, 'Corvette Mk.114', 'Price LLC', 37.29, 30);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (115, 'Grand Am Mk.115', 'Feeney, Mills and Hackett', 1.54, 92);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (116, 'Suburban 2500 Mk.116', 'Gutmann, Green and Quigley', 13.84, 106);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (117, 'B-Series Mk.117', 'Schulist-Volkman', 2.21, 110);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (118, 'Taurus Mk.118', 'Hoeger, Lockman and Skiles', 49.56, 85);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (119, 'Legend Mk.119', 'Deckow-Gislason', 14.4, 25);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (120, 'Equus Mk.120', 'Considine-Raynor', 9.25, 14);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (121, 'Yaris Mk.121', 'Feest Inc', 35.49, 106);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (122, 'Sequoia Mk.122', 'Kautzer Group', 39.8, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (123, 'Cordia Mk.123', 'Jones, Wintheiser and Schmidt', 28.31, 49);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (124, 'F250 Mk.124', 'Mohr, Mitchell and Johnston', 19.1, 6);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (125, 'Mazda3 Mk.125', 'Steuber LLC', 39.63, 80);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (126, 'Impreza WRX Mk.126', 'Berge and Sons', 26.78, 18);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (127, 'Tracker Mk.127', 'Waters, Friesen and Hane', 46.93, 120);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (128, 'Element Mk.128', 'Kohler, Senger and Haag', 28.66, 13);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (129, 'Sierra 3500 Mk.129', 'Schiller-Brakus', 23.81, 80);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (130, 'S60 Mk.130', 'Torphy, Howe and Sauer', 6.34, 58);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (131, 'Mark VIII Mk.131', 'Corwin, Green and Douglas', 31.87, 117);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (132, 'Ram 1500 Club Mk.132', 'Rempel, Runolfsdottir and Goodwin', 34.15, 48);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (133, 'Camry Hybrid Mk.133', 'Block-Wehner', 26.56, 99);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (134, 'Lumina APV Mk.134', 'West-O''Keefe', 41.68, 117);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (135, 'Mazdaspeed6 Mk.135', 'Cruickshank Group', 42.76, 4);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (136, '545 Mk.136', 'Kihn, Flatley and Hagenes', 35.74, 109);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (137, 'Quest Mk.137', 'Yost-Hyatt', 16.08, 87);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (138, 'Spyder Mk.138', 'Steuber, Harvey and Wintheiser', 14.48, 17);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (139, 'Yukon XL 2500 Mk.139', 'Macejkovic, Gleason and Howell', 44.5, 53);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (140, 'Tempo Mk.140', 'Rutherford-Herman', 30.76, 7);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (141, 'Civic Mk.141', 'Rempel, Paucek and Considine', 27.41, 110);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (142, 'ZX2 Mk.142', 'Jakubowski-Prohaska', 7.32, 7);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (143, 'Grand Prix Mk.143', 'Okuneva, Stiedemann and Bartoletti', 14.93, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (144, 'Accord Crosstour Mk.144', 'Abernathy-Labadie', 49.21, 5);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (145, 'Terrain Mk.145', 'Nikolaus and Sons', 5.44, 2);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (146, 'California Mk.146', 'Turcotte-Vandervort', 31.24, 17);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (147, 'Ram Van 1500 Mk.147', 'Schamberger LLC', 20.78, 90);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (148, 'Sonoma Mk.148', 'Parisian LLC', 44.81, 80);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (149, 'Legend Mk.149', 'Murphy Inc', 22.98, 92);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (150, 'Tucson Mk.150', 'Goldner and Sons', 7.25, 42);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (151, 'Ram Wagon B250 Mk.151', 'Carter-Beatty', 40.58, 11);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (152, 'i-350 Mk.152', 'Harvey Group', 3.44, 104);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (153, '924 S Mk.153', 'Watsica, Vandervort and Boehm', 17.73, 60);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (154, 'A6 Mk.154', 'Langworth, Schultz and Halvorson', 43.83, 6);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (155, 'Crossfire Mk.155', 'Rowe and Sons', 29.3, 88);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (156, 'Roadmaster Mk.156', 'Lehner Group', 4.73, 104);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (157, 'S-Class Mk.157', 'Conroy-MacGyver', 32.85, 105);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (158, 'IS F Mk.158', 'Wolf-Stroman', 48.28, 36);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (159, 'E-Class Mk.159', 'Fahey-MacGyver', 48.87, 80);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (160, 'Escalade EXT Mk.160', 'Skiles-Smitham', 10.2, 55);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (161, 'Passat Mk.161', 'Kshlerin Inc', 41.17, 110);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (162, 'Express Mk.162', 'Grady-Will', 37.85, 84);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (163, 'Familia Mk.163', 'Herman and Sons', 32.68, 62);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (164, 'S80 Mk.164', 'Watsica LLC', 8.84, 72);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (165, 'QX Mk.165', 'D''Amore-Sauer', 22.86, 44);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (166, 'Leaf Mk.166', 'Treutel, McDermott and O''Reilly', 40.07, 78);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (167, 'Sienna Mk.167', 'Runte, Bednar and Ankunding', 6.83, 53);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (168, 'Outlander Mk.168', 'Funk LLC', 25.62, 79);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (169, 'Altima Mk.169', 'McCullough, Wuckert and Schinner', 19.77, 23);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (170, 'CLK-Class Mk.170', 'Kuhlman-Spinka', 49.12, 93);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (171, 'Mirage Mk.171', 'Jakubowski Group', 27.74, 74);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (172, 'Yukon Mk.172', 'Johnson, Abernathy and Hilll', 37.27, 2);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (173, '300ZX Mk.173', 'Collier Inc', 28.21, 30);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (174, 'Mark VIII Mk.174', 'White Group', 31.27, 66);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (175, 'Discovery Mk.175', 'Simonis Group', 46.48, 96);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (176, 'SLK-Class Mk.176', 'Senger, Abernathy and Hauck', 7.48, 8);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (177, 'Silverado 2500 Mk.177', 'Conroy-Emard', 22.77, 16);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (178, 'Sentra Mk.178', 'Mayer-Cremin', 49.77, 24);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (179, 'Alcyone SVX Mk.179', 'Donnelly Inc', 23.47, 74);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (180, 'Savana 1500 Mk.180', 'Ondricka Inc', 36.87, 2);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (181, 'Yukon XL 1500 Mk.181', 'Abernathy and Sons', 3.45, 82);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (182, 'Thunderbird Mk.182', 'Ratke-Gleichner', 27.47, 32);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (183, 'LeSabre Mk.183', 'Gulgowski, Upton and Moore', 41.61, 96);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (184, 'Forenza Mk.184', 'King-Reilly', 1.4, 55);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (185, 'Corvette Mk.185', 'Veum Inc', 32.78, 47);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (186, 'G35 Mk.186', 'Moore, Hackett and Rice', 40.71, 3);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (187, '745 Mk.187', 'Mann LLC', 12.63, 78);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (188, 'Venza Mk.188', 'Smith, Graham and Kemmer', 24.26, 18);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (189, 'Escape Mk.189', 'Rodriguez-Zemlak', 35.27, 58);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (190, 'Econoline E150 Mk.190', 'Kuphal-Murazik', 24.74, 18);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (191, 'Stratus Mk.191', 'Langosh LLC', 49.11, 63);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (192, 'Murano Mk.192', 'Bechtelar-Hodkiewicz', 34.56, 41);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (193, 'Town & Country Mk.193', 'Larkin and Sons', 37.97, 114);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (194, 'HS Mk.194', 'Bailey-Jerde', 46.95, 17);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (195, 'Tredia Mk.195', 'Grimes-Wiza', 41.96, 13);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (196, 'Century Mk.196', 'Grady, Spencer and Sanford', 42.13, 93);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (197, 'SJ Mk.197', 'Schiller-Hilpert', 47.81, 40);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (198, '940 Mk.198', 'Romaguera-Monahan', 24.78, 108);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (199, 'Fortwo Mk.199', 'O''Kon-Kulas', 7.49, 66);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (200, 'SL-Class Mk.200', 'Hudson, Murphy and D''Amore', 16.69, 91);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (201, 'RX Mk.201', 'Toy, Bailey and Auer', 39.82, 114);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (202, 'Crown Victoria Mk.202', 'Mann Group', 21.94, 114);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (203, 'Prius Mk.203', 'Beer-Bosco', 45.61, 43);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (204, '3500 Mk.204', 'Turner-Durgan', 8.28, 82);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (205, 'Insight Mk.205', 'Botsford, Tromp and O''Kon', 9.32, 40);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (206, 'S-Series Mk.206', 'Smitham and Sons', 11.72, 110);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (207, 'XL-7 Mk.207', 'Strosin and Sons', 47.99, 70);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (208, 'G6 Mk.208', 'Okuneva-Waters', 18.59, 45);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (209, 'Savana Mk.209', 'Lang, Jaskolski and Sawayn', 24.4, 6);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (210, 'XLR Mk.210', 'Rolfson and Sons', 12.14, 62);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (211, 'Firefly Mk.211', 'Greenholt, Kertzmann and Crist', 45.26, 19);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (212, '900 Mk.212', 'Stroman, Parker and Heller', 15.02, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (213, 'Fiero Mk.213', 'Steuber and Sons', 10.76, 84);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (214, 'TL Mk.214', 'DuBuque Inc', 46.8, 70);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (215, 'Lucerne Mk.215', 'Lesch Inc', 36.01, 96);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (216, '2500 Mk.216', 'Hahn-Little', 13.37, 39);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (217, 'LeSabre Mk.217', 'Goodwin LLC', 3.53, 47);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (218, '300M Mk.218', 'Bartell, Lynch and Fisher', 20.89, 114);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (219, 'Passat Mk.219', 'Rempel, Greenfelder and Gleason', 40.84, 74);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (220, 'Suburban 2500 Mk.220', 'Shanahan-Nikolaus', 18.12, 87);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (221, 'Titan Mk.221', 'Lockman-Kulas', 13.26, 49);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (222, 'Neon Mk.222', 'Grimes-Romaguera', 42.83, 38);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (223, 'Insight Mk.223', 'Christiansen LLC', 15.3, 91);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (224, 'E-Class Mk.224', 'Klein and Sons', 46.79, 120);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (225, 'XL7 Mk.225', 'Grant Group', 46.03, 102);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (226, 'Town Car Mk.226', 'Marquardt Inc', 31.32, 49);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (227, 'Chariot Mk.227', 'Considine, Koch and Baumbach', 46.57, 65);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (228, 'Skyhawk Mk.228', 'Walter LLC', 13.89, 113);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (229, 'Camry Mk.229', 'VonRueden and Sons', 20.1, 94);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (230, 'Leganza Mk.230', 'Lindgren Inc', 17.18, 28);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (231, 'CT Mk.231', 'Gutmann Inc', 40.31, 31);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (232, 'Versa Mk.232', 'Klocko and Sons', 49.44, 52);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (233, 'B-Series Plus Mk.233', 'Breitenberg, Yost and Welch', 47.08, 14);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (234, 'Express 2500 Mk.234', 'Padberg-Durgan', 16.77, 50);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (235, 'Escape Mk.235', 'Balistreri, West and Weimann', 0.19, 101);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (236, 'GX Mk.236', 'Ward, Nader and Greenholt', 34.12, 24);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (237, 'Passat Mk.237', 'Towne and Sons', 22.49, 84);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (238, 'Tracker Mk.238', 'Cartwright-Bergstrom', 42.93, 85);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (239, '350Z Mk.239', 'Kilback-Lueilwitz', 40.49, 68);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (240, 'Silverado 3500 Mk.240', 'D''Amore Group', 15.75, 50);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (241, 'Golf Mk.241', 'Rau-Cormier', 0.55, 6);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (242, 'Suburban 2500 Mk.242', 'Reinger, Hermiston and Cassin', 36.44, 87);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (243, 'Malibu Mk.243', 'Halvorson-Hammes', 24.96, 90);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (244, 'Corolla Mk.244', 'Shanahan, D''Amore and Hyatt', 14.94, 6);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (245, 'XC70 Mk.245', 'Turner-Swaniawski', 26.78, 26);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (246, 'Patriot Mk.246', 'Collins Group', 20.61, 71);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (247, 'Camaro Mk.247', 'Stiedemann, Flatley and Thompson', 6.78, 120);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (248, 'Golf Mk.248', 'Gerhold, Strosin and Leuschke', 34.66, 120);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (249, 'Phantom Mk.249', 'Roberts LLC', 31.19, 43);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (250, 'F150 Mk.250', 'Bergnaum and Sons', 14.39, 39);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (251, 'G6 Mk.251', 'Dare-Watsica', 8.98, 10);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (252, 'LS Hybrid Mk.252', 'Bahringer Inc', 32.78, 73);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (253, 'Cooper Mk.253', 'Spinka-Hilll', 46.83, 41);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (254, 'I Mk.254', 'Hickle, Rogahn and Keebler', 29.59, 5);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (255, '599 GTB Fiorano Mk.255', 'O''Conner LLC', 26.23, 80);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (256, 'Mustang Mk.256', 'Walter, Schinner and Kozey', 2.22, 63);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (257, 'Fit Mk.257', 'Leffler Group', 30.07, 30);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (258, 'LeSabre Mk.258', 'Herman, Wisoky and Kutch', 16.97, 110);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (259, 'xD Mk.259', 'Shields, Thompson and Brakus', 33.79, 56);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (260, 'Firefly Mk.260', 'Rowe, Kuhn and Kovacek', 13.01, 73);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (261, '929 Mk.261', 'Greenholt Inc', 17.92, 103);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (262, 'A6 Mk.262', 'Dicki, Daniel and Sipes', 14.59, 116);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (263, 'Grand Cherokee Mk.263', 'Homenick and Sons', 20.32, 42);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (264, 'Accord Mk.264', 'Marvin, Glover and Mraz', 16.43, 82);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (265, 'Baja Mk.265', 'Bashirian and Sons', 16.72, 75);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (266, 'LSS Mk.266', 'Orn-Beer', 28.0, 51);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (267, 'Tribeca Mk.267', 'Jacobson, White and Ebert', 4.3, 48);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (268, 'Expedition EL Mk.268', 'Bernhard, Kuhn and Hickle', 18.88, 101);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (269, '900 Mk.269', 'Becker-Veum', 34.54, 86);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (270, 'CTS Mk.270', 'Jenkins-Kovacek', 19.98, 4);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (271, 'Capri Mk.271', 'Rempel, Bahringer and Schneider', 14.65, 69);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (272, 'Sebring Mk.272', 'Daugherty, Wilderman and Doyle', 19.95, 10);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (273, 'Mazda5 Mk.273', 'Krajcik-Morar', 38.72, 101);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (274, 'Equator Mk.274', 'Welch-Wilderman', 28.84, 118);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (275, '911 Mk.275', 'Bernier, Skiles and Sanford', 41.9, 96);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (276, 'Ram 1500 Mk.276', 'Hartmann-Anderson', 47.04, 86);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (277, '6 Series Mk.277', 'Bayer, Bailey and Steuber', 25.46, 92);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (278, 'Scirocco Mk.278', 'Herzog LLC', 46.92, 21);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (279, 'Ram 1500 Club Mk.279', 'Doyle Inc', 18.17, 98);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (280, 'Caprice Mk.280', 'Hamill Inc', 25.91, 31);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (281, 'Taurus Mk.281', 'Boyle, Turcotte and Waelchi', 2.43, 48);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (282, 'S10 Blazer Mk.282', 'Kuhn, Morissette and Koelpin', 20.66, 104);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (283, 'Carens Mk.283', 'Kovacek and Sons', 1.73, 75);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (284, 'Grand Cherokee Mk.284', 'Schulist, Conroy and Heaney', 42.49, 7);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (285, 'MX-5 Mk.285', 'Boehm-Swaniawski', 43.14, 17);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (286, 'QX Mk.286', 'Lind Inc', 28.04, 76);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (287, 'XK Mk.287', 'Murazik-Stracke', 5.92, 33);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (288, 'Phantom Mk.288', 'O''Hara, Rowe and Dooley', 36.73, 30);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (289, 'Yukon Mk.289', 'Kassulke Group', 16.32, 93);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (290, 'XC70 Mk.290', 'Brekke-Bruen', 35.45, 99);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (291, 'Truck Mk.291', 'Langosh Group', 8.28, 6);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (292, 'Swift Mk.292', 'Nikolaus-Predovic', 46.5, 102);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (293, 'Tercel Mk.293', 'Schimmel LLC', 22.55, 87);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (294, 'Jetta Mk.294', 'Green-Runte', 18.44, 45);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (295, 'Accent Mk.295', 'Gerlach, Prosacco and Hegmann', 49.34, 115);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (296, 'Probe Mk.296', 'Runte, Balistreri and Reilly', 4.61, 64);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (297, 'E-Class Mk.297', 'Kovacek-Leffler', 11.41, 61);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (298, 'Yukon Mk.298', 'Tremblay-Murphy', 6.95, 72);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (299, '330 Mk.299', 'Herzog-Kreiger', 28.31, 3);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (300, 'Savana 1500 Mk.300', 'Huels-Rice', 31.9, 7);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (301, 'Envoy Mk.301', 'Olson, Hayes and Von', 16.86, 9);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (302, 'Legacy Mk.302', 'Wolf and Sons', 30.44, 104);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (303, 'Liberty Mk.303', 'Gorczany LLC', 4.89, 13);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (304, 'L300 Mk.304', 'Carroll LLC', 25.11, 91);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (305, 'SRX Mk.305', 'Kiehn LLC', 44.15, 62);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (306, 'Camaro Mk.306', 'Gorczany-Weimann', 23.86, 11);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (307, 'DB9 Mk.307', 'Boyer LLC', 1.2, 70);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (308, '5 Series Mk.308', 'Will, Anderson and Wisozk', 28.95, 51);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (309, 'Explorer Sport Trac Mk.309', 'Hahn-Gislason', 30.92, 14);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (310, 'Metro Mk.310', 'McKenzie, Johnston and Zboncak', 43.47, 41);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (311, 'Sonoma Mk.311', 'Boehm, Zemlak and Braun', 34.32, 60);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (312, 'Civic Mk.312', 'Marvin-Deckow', 9.77, 27);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (313, 'Fusion Mk.313', 'Feeney, Doyle and Kub', 46.02, 100);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (314, 'SLR McLaren Mk.314', 'Champlin, Fay and Koepp', 26.36, 13);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (315, 'A3 Mk.315', 'Langworth-Mayer', 35.23, 117);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (316, 'Continental GTC Mk.316', 'Wolff Inc', 23.31, 84);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (317, 'Avalanche 1500 Mk.317', 'Tremblay Inc', 5.98, 97);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (318, 'L300 Mk.318', 'Lehner Inc', 16.48, 22);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (319, 'Expedition Mk.319', 'Runolfsdottir-Boehm', 42.78, 71);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (320, 'Truck Mk.320', 'Walsh-Waters', 13.0, 42);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (321, 'Suburban 2500 Mk.321', 'Padberg Group', 14.85, 112);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (322, 'TrailBlazer Mk.322', 'Hodkiewicz, Lueilwitz and Emmerich', 27.63, 58);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (323, 'Topaz Mk.323', 'Parker and Sons', 26.97, 15);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (324, '240SX Mk.324', 'Schulist-Kuvalis', 21.47, 60);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (325, 'Insight Mk.325', 'Baumbach-Herman', 10.82, 48);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (326, 'Tucson Mk.326', 'Grant, Swift and Fritsch', 26.68, 13);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (327, 'Thunderbird Mk.327', 'Franecki, Ullrich and Williamson', 11.9, 58);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (328, 'X3 Mk.328', 'Nolan, Johnson and Carter', 10.7, 28);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (329, 'Riviera Mk.329', 'Dickinson-Veum', 18.08, 80);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (330, 'Altima Mk.330', 'Doyle, Becker and Metz', 34.76, 9);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (331, 'LS Mk.331', 'Marvin, Fritsch and Zulauf', 9.33, 95);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (332, 'Corsica Mk.332', 'Wisoky LLC', 18.13, 19);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (333, 'Capri Mk.333', 'Price, Dickens and Feest', 11.12, 30);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (334, '9-2X Mk.334', 'Gerhold Group', 27.41, 30);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (335, 'Datsun/Nissan Z-car Mk.335', 'Kreiger Group', 1.97, 44);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (336, 'SC Mk.336', 'Reichert LLC', 39.75, 113);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (337, '88 Mk.337', 'Tromp-Osinski', 34.98, 86);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (338, 'S60 Mk.338', 'Marvin, Reilly and Armstrong', 24.34, 85);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (339, 'Pathfinder Mk.339', 'Nienow Group', 43.05, 23);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (340, 'Mulsanne Mk.340', 'Feest-Borer', 12.16, 33);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (341, 'C-Class Mk.341', 'Schaden, Kuvalis and Emmerich', 47.79, 16);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (342, 'Probe Mk.342', 'Heidenreich-Jones', 19.17, 15);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (343, 'Civic Si Mk.343', 'Monahan-Jacobi', 3.93, 11);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (344, 'Yukon XL 1500 Mk.344', 'Satterfield and Sons', 20.41, 17);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (345, 'Elantra Mk.345', 'Labadie, Lind and O''Reilly', 23.2, 36);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (346, 'Bronco Mk.346', 'Casper Inc', 9.07, 20);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (347, 'Dakota Mk.347', 'Adams, Lindgren and Bednar', 41.24, 35);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (348, 'A5 Mk.348', 'Kuhn Group', 17.13, 90);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (349, 'Rodeo Sport Mk.349', 'Green, Quitzon and Boehm', 8.38, 100);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (350, 'CL Mk.350', 'Wyman, Schmitt and Hagenes', 46.94, 115);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (351, 'Hombre Space Mk.351', 'Beer, Mosciski and Ebert', 19.62, 23);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (352, 'Forester Mk.352', 'Lueilwitz Inc', 3.59, 66);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (353, 'Hombre Mk.353', 'Daugherty-Schultz', 21.29, 29);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (354, 'Escalade ESV Mk.354', 'Boyle, Altenwerth and Koch', 3.44, 105);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (355, 'Blazer Mk.355', 'Wolf, Deckow and Greenfelder', 10.2, 75);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (356, 'M6 Mk.356', 'Hermiston Group', 35.21, 49);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (357, 'Z4 Mk.357', 'Runte, Parker and Kuphal', 18.78, 102);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (358, '300SD Mk.358', 'Yost-Zboncak', 23.61, 24);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (359, '2500 Mk.359', 'Hodkiewicz LLC', 46.3, 88);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (360, 'Frontier Mk.360', 'Schuster-West', 38.43, 74);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (361, 'Grand Prix Mk.361', 'Cole-Sporer', 28.07, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (362, 'Volare Mk.362', 'Bartell LLC', 10.22, 11);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (363, '600 Mk.363', 'Borer and Sons', 41.16, 35);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (364, 'Lumina Mk.364', 'Kreiger, Hettinger and Schuster', 4.34, 109);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (365, 'Pajero Mk.365', 'Carter LLC', 0.71, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (366, 'F450 Mk.366', 'Toy, Bauch and Sauer', 1.53, 96);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (367, 'Mirage Mk.367', 'Stiedemann, Ondricka and Cremin', 35.59, 40);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (368, 'Vibe Mk.368', 'Predovic and Sons', 6.44, 87);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (369, 'S6 Mk.369', 'Nikolaus, Little and Rolfson', 44.33, 93);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (370, 'Edge Mk.370', 'Ratke-Reichel', 5.86, 87);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (371, 'Montana Mk.371', 'Lynch LLC', 31.45, 112);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (372, 'Firebird Mk.372', 'DuBuque, Mohr and Herman', 9.92, 97);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (373, 'Uplander Mk.373', 'Wuckert, Fritsch and Marks', 1.5, 93);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (374, 'Mustang Mk.374', 'Murray-Corkery', 44.61, 49);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (375, 'Elise Mk.375', 'McCullough, Keeling and Wuckert', 18.81, 85);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (376, 'Avalon Mk.376', 'Kirlin Inc', 45.54, 102);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (377, 'Sebring Mk.377', 'Kunde, Bashirian and Ledner', 45.61, 68);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (378, 'Vandura 2500 Mk.378', 'Tillman and Sons', 33.76, 80);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (379, 'Tercel Mk.379', 'Reilly Inc', 23.6, 26);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (380, 'Corvette Mk.380', 'Dickens, Rowe and Hamill', 19.89, 103);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (381, 'Discovery Mk.381', 'Jenkins-Wolf', 7.65, 60);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (382, 'Corvette Mk.382', 'Bauch Inc', 3.75, 12);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (383, 'Tacoma Xtra Mk.383', 'Hamill, Howe and Lemke', 36.8, 41);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (384, 'MX-3 Mk.384', 'Zboncak, Schmeler and Lindgren', 35.46, 86);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (385, 'C-Class Mk.385', 'Beer-Morar', 18.91, 37);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (386, '911 Mk.386', 'Walter and Sons', 1.23, 58);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (387, 'Jetta Mk.387', 'Rodriguez-Carroll', 2.02, 84);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (388, 'Falcon Mk.388', 'Ryan-Hudson', 5.07, 8);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (389, 'NSX Mk.389', 'Boyle, Schowalter and Vandervort', 5.27, 72);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (390, 'Sunfire Mk.390', 'Kuphal-Buckridge', 8.49, 90);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (391, 'Durango Mk.391', 'Upton, Anderson and Gutkowski', 3.92, 54);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (392, 'Prelude Mk.392', 'Littel-Harvey', 24.48, 42);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (393, 'Suburban 1500 Mk.393', 'Leannon, McLaughlin and Gutkowski', 17.51, 86);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (394, 'Ranger Mk.394', 'Wilderman-Conroy', 15.22, 20);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (395, 'Voyager Mk.395', 'Emard-Welch', 33.86, 56);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (396, 'Rio Mk.396', 'Mante Group', 42.12, 54);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (397, 'Century Mk.397', 'Jerde-Lakin', 38.54, 59);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (398, 'Sportvan G10 Mk.398', 'Fritsch Inc', 28.79, 31);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (399, 'MDX Mk.399', 'Murazik Inc', 28.11, 48);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (400, 'Gallardo Mk.400', 'Homenick, Rempel and Morissette', 29.54, 5);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (401, 'Sedona Mk.401', 'Hand-Walsh', 12.41, 39);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (402, 'Amigo Mk.402', 'Emard-Roberts', 19.34, 48);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (403, 'Corolla Mk.403', 'Kessler, Connelly and Jaskolski', 39.95, 65);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (404, 'Escalade Mk.404', 'Klocko Inc', 18.14, 105);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (405, 'DeVille Mk.405', 'Roob-Heathcote', 16.1, 42);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (406, '968 Mk.406', 'Ebert-Schmitt', 39.52, 81);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (407, 'Cooper Clubman Mk.407', 'Keebler, Haag and Jones', 34.29, 83);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (408, 'Durango Mk.408', 'Pollich and Sons', 40.67, 106);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (409, 'Savana Mk.409', 'Nitzsche, Ward and Runte', 15.96, 81);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (410, 'Boxster Mk.410', 'Lakin Group', 34.91, 8);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (411, 'Silverado 1500 Mk.411', 'Turner, Haley and Durgan', 46.29, 111);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (412, 'Silverado 2500 Mk.412', 'Lesch Group', 18.64, 66);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (413, 'QX Mk.413', 'Wyman and Sons', 36.28, 26);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (414, 'Ion Mk.414', 'Schaden-McKenzie', 29.29, 14);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (415, 'Civic Mk.415', 'Mante-Langworth', 34.65, 69);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (416, 'V50 Mk.416', 'Kozey Group', 9.08, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (417, '200SX Mk.417', 'Bartell, Muller and Hermann', 33.6, 98);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (418, 'Focus Mk.418', 'Johnston-Dickens', 32.94, 78);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (419, 'Optima Mk.419', 'Bradtke Inc', 20.76, 102);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (420, 'M Mk.420', 'Hettinger-Ritchie', 41.58, 36);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (421, 'Boxster Mk.421', 'Gerlach Inc', 17.74, 63);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (422, '300ZX Mk.422', 'Kirlin Inc', 20.74, 35);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (423, 'Traverse Mk.423', 'Satterfield LLC', 28.4, 15);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (424, 'Baja Mk.424', 'Jenkins Group', 27.88, 51);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (425, 'Explorer Mk.425', 'Becker and Sons', 11.76, 11);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (426, 'Jetta Mk.426', 'Stark, Hayes and Skiles', 46.43, 60);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (427, 'Escalade Mk.427', 'Tremblay, Green and Hessel', 7.73, 55);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (428, 'Cooper Mk.428', 'Quitzon, Little and Windler', 47.03, 75);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (429, 'Elan Mk.429', 'Heaney, Aufderhar and Mann', 4.75, 79);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (430, 'Caravan Mk.430', 'Walker Group', 48.54, 119);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (431, 'SC Mk.431', 'Murazik, Renner and Bahringer', 25.39, 112);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (432, 'Lancer Mk.432', 'Toy-Bogan', 33.62, 69);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (433, 'Mustang Mk.433', 'Rice, Hackett and Schuppe', 44.24, 11);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (434, 'Equinox Mk.434', 'Boehm Inc', 40.31, 50);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (435, 'E150 Mk.435', 'Quigley-Keebler', 20.31, 25);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (436, 'E250 Mk.436', 'Padberg Group', 8.9, 98);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (437, 'XC90 Mk.437', 'Douglas-Ledner', 15.07, 106);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (438, 'Sunbird Mk.438', 'Stiedemann, Schulist and Hackett', 31.83, 33);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (439, 'Galant Mk.439', 'Frami, Kuhn and Mueller', 11.06, 21);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (440, 'S5 Mk.440', 'Beier Inc', 28.05, 24);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (441, 'LTD Crown Victoria Mk.441', 'Wolff, Larkin and Runte', 32.38, 29);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (442, 'Diablo Mk.442', 'Brekke and Sons', 30.39, 13);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (443, 'Optima Mk.443', 'Hand-Balistreri', 11.88, 37);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (444, 'CLK-Class Mk.444', 'Wyman LLC', 20.44, 98);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (445, 'Town & Country Mk.445', 'Daniel Inc', 13.8, 76);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (446, 'XJ Series Mk.446', 'Hackett, Wiegand and Watsica', 26.83, 12);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (447, '2500 Mk.447', 'Schowalter, Runolfsdottir and Schroeder', 8.68, 63);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (448, 'TrailBlazer Mk.448', 'Nienow Group', 40.46, 58);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (449, 'Ram 1500 Mk.449', 'Johnson LLC', 9.03, 38);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (450, 'Range Rover Mk.450', 'Weimann, Cole and Leffler', 37.45, 58);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (451, '90 Mk.451', 'Considine-Gleason', 20.14, 37);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (452, 'RX Mk.452', 'Feest Group', 11.42, 63);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (453, 'Vitara Mk.453', 'Ryan and Sons', 19.14, 24);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (454, '3500 Mk.454', 'Mraz-Jacobi', 2.88, 21);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (455, 'Estate Mk.455', 'Brown-Hilpert', 1.27, 8);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (456, 'LHS Mk.456', 'Auer Inc', 35.35, 81);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (457, 'Space Mk.457', 'Cole-Hermann', 27.3, 119);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (458, 'Riviera Mk.458', 'Price Group', 16.13, 26);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (459, 'Aveo Mk.459', 'Rippin-Schamberger', 15.07, 31);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (460, 'Mazda3 Mk.460', 'Prohaska, Fahey and McGlynn', 39.94, 62);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (461, 'Avenger Mk.461', 'Christiansen, Mosciski and Stanton', 18.93, 65);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (462, 'Regal Mk.462', 'Heathcote, Schulist and Hansen', 45.73, 118);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (463, 'Continental Mk.463', 'Treutel Inc', 4.97, 70);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (464, 'Legacy Mk.464', 'Prosacco, Runolfsson and Ankunding', 29.39, 104);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (465, '600 Mk.465', 'Hodkiewicz Inc', 21.88, 111);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (466, 'Bonneville Mk.466', 'Hermiston-Smitham', 38.89, 39);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (467, 'Explorer Mk.467', 'Lynch, Dietrich and Rohan', 23.22, 73);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (468, 'Silhouette Mk.468', 'Dooley Group', 31.37, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (469, '164 Mk.469', 'Okuneva-Morissette', 38.29, 84);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (470, 'GTI Mk.470', 'Purdy-Feil', 22.82, 81);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (471, 'MKS Mk.471', 'Turcotte-Hickle', 49.75, 1);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (472, 'Escalade Mk.472', 'Stehr-Predovic', 9.73, 75);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (473, 'F150 Mk.473', 'Jast-Torp', 16.8, 51);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (474, 'S-Class Mk.474', 'Stehr-Flatley', 49.4, 21);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (475, 'Civic Mk.475', 'Olson LLC', 38.08, 33);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (476, 'Biturbo Mk.476', 'Hane, Yost and Emmerich', 15.5, 33);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (477, 'New Yorker Mk.477', 'Durgan-Hyatt', 41.9, 32);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (478, 'Carens Mk.478', 'Moen-Lakin', 10.77, 101);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (479, 'Sundance Mk.479', 'Gleichner-Terry', 49.47, 32);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (480, 'GL-Class Mk.480', 'Bins LLC', 23.69, 68);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (481, 'Civic Mk.481', 'Lubowitz-Rogahn', 10.22, 22);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (482, '944 Mk.482', 'Schamberger-Lindgren', 8.72, 17);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (483, 'Sportage Mk.483', 'Boehm-Champlin', 40.85, 104);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (484, 'del Sol Mk.484', 'Armstrong-Ortiz', 20.67, 69);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (485, 'MKZ Mk.485', 'Flatley-Heidenreich', 45.68, 19);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (486, 'Pajero Mk.486', 'Veum LLC', 17.54, 83);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (487, 'RS4 Mk.487', 'Greenfelder, Howe and Stracke', 16.16, 27);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (488, 'C-Class Mk.488', 'Casper, Armstrong and Braun', 30.04, 105);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (489, '911 Mk.489', 'Kuhlman-Larson', 34.13, 52);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (490, 'TSX Mk.490', 'Casper Inc', 42.97, 17);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (491, 'Accord Mk.491', 'Bins-Rowe', 28.8, 91);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (492, 'Sierra 1500 Mk.492', 'Ankunding, Considine and Wisoky', 28.77, 78);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (493, '2500 Mk.493', 'Kuvalis, Becker and Dickinson', 17.84, 1);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (494, 'Quest Mk.494', 'Cruickshank, Barrows and Reilly', 16.35, 82);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (495, 'H3T Mk.495', 'Yundt and Sons', 48.05, 32);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (496, 'Liberty Mk.496', 'Kunze-Dooley', 29.91, 4);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (497, 'Cavalier Mk.497', 'Beahan, Ryan and Davis', 24.73, 83);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (498, 'XL-7 Mk.498', 'Howell and Sons', 33.99, 8);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (499, 'Jetta Mk.499', 'Smitham, Ondricka and Leffler', 20.26, 1);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (500, 'MDX Mk.500', 'Nitzsche and Sons', 33.78, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (501, 'Odyssey Mk.501', 'Bechtelar, Schneider and Jakubowski', 49.34, 14);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (502, 'Sunfire Mk.502', 'Kuhlman LLC', 28.88, 7);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (503, 'Dakota Club Mk.503', 'Kozey-Hauck', 48.61, 31);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (504, 'RAV4 Mk.504', 'Weber-Wyman', 26.89, 8);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (505, 'Savana 1500 Mk.505', 'Rice LLC', 39.83, 33);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (506, 'XC60 Mk.506', 'Bernier, Zboncak and Roberts', 24.62, 11);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (507, '300M Mk.507', 'White Group', 14.04, 44);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (508, 'S-Series Mk.508', 'Paucek and Sons', 24.96, 62);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (509, 'MKS Mk.509', 'Hayes-Becker', 38.76, 31);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (510, 'E150 Mk.510', 'Veum Inc', 6.66, 63);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (511, 'STS-V Mk.511', 'McGlynn-Erdman', 26.93, 74);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (512, 'Rodeo Mk.512', 'Rowe, Williamson and Ebert', 39.93, 108);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (513, 'Montero Mk.513', 'Kunze Inc', 32.96, 4);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (514, 'E150 Mk.514', 'Ullrich-Willms', 21.21, 75);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (515, 'FX Mk.515', 'Kihn LLC', 7.13, 70);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (516, 'Wrangler Mk.516', 'Armstrong, Metz and Daugherty', 5.12, 112);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (517, 'Civic Mk.517', 'Donnelly Inc', 49.48, 119);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (518, '911 Mk.518', 'Boehm, O''Reilly and Christiansen', 26.08, 29);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (519, 'Pajero Mk.519', 'Bailey-Hettinger', 16.4, 65);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (520, 'Sebring Mk.520', 'Mohr-Schuppe', 11.71, 87);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (521, 'LR2 Mk.521', 'Langworth, Kerluke and Hodkiewicz', 5.78, 16);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (522, 'xB Mk.522', 'Altenwerth-Welch', 15.62, 87);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (523, 'Caravan Mk.523', 'Cronin Inc', 17.12, 62);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (524, 'Scirocco Mk.524', 'McKenzie-Strosin', 21.35, 7);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (525, 'Corvette Mk.525', 'Larkin and Sons', 34.75, 113);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (526, 'Mystique Mk.526', 'Raynor, Dibbert and Leannon', 40.9, 31);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (527, '5 Series Mk.527', 'Cartwright Group', 35.4, 9);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (528, 'Rio Mk.528', 'Waelchi, Marvin and Schaden', 32.86, 100);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (529, 'Windstar Mk.529', 'Hodkiewicz LLC', 28.15, 45);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (530, '62 Mk.530', 'Harber-Dietrich', 24.25, 12);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (531, 'Riviera Mk.531', 'Klein Inc', 44.7, 63);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (532, 'MX-3 Mk.532', 'Cruickshank LLC', 0.28, 7);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (533, 'Silverado 2500 Mk.533', 'Hane, Sanford and Fay', 8.91, 57);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (534, 'Forte Mk.534', 'Stehr-Carter', 21.99, 19);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (535, 'Corvette Mk.535', 'Adams-Pfeffer', 49.38, 43);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (536, 'SC Mk.536', 'Lebsack-Bernier', 3.36, 99);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (537, 'Spirit Mk.537', 'Harris, Dickens and Runolfsson', 43.11, 117);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (538, 'Escort Mk.538', 'Green-Collier', 1.75, 61);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (539, 'G-Series G10 Mk.539', 'Shanahan Inc', 7.13, 107);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (540, 'Integra Mk.540', 'Schinner Group', 9.52, 117);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (541, 'Lucerne Mk.541', 'Homenick, Terry and Bergnaum', 29.06, 41);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (542, 'LR4 Mk.542', 'Kautzer and Sons', 30.13, 81);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (543, '1500 Mk.543', 'Torphy, Fisher and Spinka', 0.57, 88);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (544, 'Intrigue Mk.544', 'Spencer-Hyatt', 45.15, 82);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (545, 'Expedition Mk.545', 'Thiel, Klein and O''Connell', 44.79, 81);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (546, 'L300 Mk.546', 'Dibbert-Gutkowski', 38.41, 58);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (547, 'Solara Mk.547', 'Pacocha, Grimes and Fahey', 22.85, 111);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (548, 'Armada Mk.548', 'Oberbrunner, Bergstrom and Davis', 26.96, 109);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (549, 'xB Mk.549', 'Doyle, McDermott and Ryan', 21.81, 59);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (550, 'Five Hundred Mk.550', 'Rohan-Kreiger', 24.53, 30);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (551, 'Miata MX-5 Mk.551', 'Batz LLC', 38.69, 6);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (552, 'Grand Am Mk.552', 'Erdman, Nolan and Kemmer', 32.96, 91);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (553, 'Terraza Mk.553', 'Leannon LLC', 29.45, 30);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (554, 'Sierra 2500 Mk.554', 'Barrows LLC', 36.5, 83);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (555, 'Trooper Mk.555', 'Stokes, Hauck and Quitzon', 39.03, 5);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (556, 'Neon Mk.556', 'Frami-Wiegand', 25.98, 10);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (557, 'Civic Mk.557', 'Kutch-Douglas', 22.5, 9);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (558, 'B-Series Plus Mk.558', 'Stoltenberg-Olson', 15.71, 48);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (559, 'VUE Mk.559', 'Stracke, Renner and Bailey', 15.59, 69);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (560, 'F150 Mk.560', 'Hilpert and Sons', 15.46, 12);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (561, 'RSX Mk.561', 'Denesik-Raynor', 45.21, 96);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (562, 'TSX Mk.562', 'Heidenreich-Ziemann', 14.1, 34);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (563, 'Impreza WRX Mk.563', 'Moen Inc', 26.07, 110);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (564, 'XL-7 Mk.564', 'Rau-Simonis', 22.66, 2);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (565, 'Cobalt Mk.565', 'Williamson, Deckow and Pollich', 36.7, 94);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (566, 'Tucson Mk.566', 'Runte, Romaguera and Rice', 48.34, 21);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (567, 'Camaro Mk.567', 'Schneider Group', 13.22, 50);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (568, 'W201 Mk.568', 'Boyle LLC', 13.44, 29);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (569, 'E-Class Mk.569', 'O''Reilly-Padberg', 29.02, 14);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (570, 'D150 Mk.570', 'Prohaska Group', 11.38, 93);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (571, '88 Mk.571', 'Herman-Kuphal', 46.48, 46);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (572, 'Pilot Mk.572', 'Okuneva-Orn', 35.01, 116);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (573, 'Firebird Mk.573', 'Lueilwitz-Rippin', 25.4, 81);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (574, 'Truck Mk.574', 'Goyette Inc', 8.54, 90);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (575, 'Vantage Mk.575', 'Gerlach Group', 13.7, 5);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (576, 'B2600 Mk.576', 'Swift, Sauer and Feil', 45.03, 32);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (577, 'Blazer Mk.577', 'Cole-Veum', 18.34, 104);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (578, 'R32 Mk.578', 'Smith, Stanton and Beer', 3.37, 77);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (579, '90 Mk.579', 'Legros Group', 41.71, 73);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (580, '900 Mk.580', 'Murray-Ratke', 14.14, 60);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (581, 'RX-7 Mk.581', 'Abernathy, Douglas and Ruecker', 24.54, 81);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (582, 'Seville Mk.582', 'Towne Group', 13.57, 25);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (583, 'Truck Mk.583', 'Yost-Kreiger', 14.54, 66);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (584, 'Civic Mk.584', 'Gusikowski, Prohaska and Bashirian', 33.49, 19);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (585, 'Sienna Mk.585', 'Keeling, O''Conner and Herzog', 19.9, 20);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (586, 'Parisienne Mk.586', 'Goyette Group', 36.5, 68);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (587, 'Fairlane Mk.587', 'West LLC', 26.47, 102);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (588, 'Econoline E250 Mk.588', 'Senger LLC', 36.41, 111);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (589, 'Aspire Mk.589', 'Veum Inc', 13.33, 98);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (590, 'Sephia Mk.590', 'Treutel, Hintz and Dibbert', 12.84, 78);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (591, 'Rodeo Sport Mk.591', 'Torphy Group', 6.31, 104);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (592, 'Corvette Mk.592', 'Herzog, Upton and Mitchell', 32.07, 15);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (593, 'Challenger Mk.593', 'Smitham, Beier and Buckridge', 20.47, 32);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (594, 'Achieva Mk.594', 'Hansen, Mills and Jacobi', 34.78, 102);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (595, 'Expedition EL Mk.595', 'McLaughlin Group', 33.29, 24);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (596, 'Santa Fe Mk.596', 'Hermiston-Roberts', 48.4, 43);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (597, 'Quattroporte Mk.597', 'Cormier, Kirlin and Corkery', 5.3, 12);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (598, 'CX-7 Mk.598', 'Tremblay Group', 19.94, 31);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (599, 'Durango Mk.599', 'Bahringer, Haley and Flatley', 35.54, 2);
insert into DRONE_MODELS (Model_ID, Model_Name, Manufacturer, Max_Payload_Weight, Max_Flight_Time) values (600, 'Astro Mk.600', 'Osinski Group', 26.03, 15);
