insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (101, '2025-11-19', 4, 'ut blandit', 552);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (102, '2025-10-13', 5, 'egestas metus aenean', 416);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (103, '2025-11-28', 5, 'sit amet eleifend', 420);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (104, '2025-10-21', 5, 'sed tristique in', 501);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (105, '2026-04-02', 1, 'nulla ultrices aliquet', 558);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (106, '2026-02-26', 5, 'ut mauris eget', 219);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (107, '2026-02-17', 3, 'turpis a pede posuere', 166);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (108, '2026-01-09', 5, 'vitae nisi', 166);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (109, '2025-12-14', 2, 'sed interdum venenatis', 578);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (110, '2025-11-30', 2, 'elit ac nulla sed', 222);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (111, '2025-12-07', 3, 'primis in faucibus orci luctus', 363);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (112, '2026-02-11', 1, 'ipsum ac tellus semper', 580);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (113, '2025-11-25', 1, 'turpis a pede', 300);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (114, '2026-02-24', 3, 'tellus in sagittis dui', 499);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (115, '2026-02-06', 1, 'nam nulla integer', 114);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (116, '2025-10-19', 4, 'nibh in lectus pellentesque', 245);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (117, '2026-01-28', 4, 'varius ut blandit non', 422);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (118, '2026-01-31', 1, 'aliquam lacus morbi quis', 452);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (119, '2025-10-27', 4, 'augue quam', 213);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (120, '2025-10-25', 1, 'ac diam cras', 292);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (121, '2026-02-19', 1, 'vel pede morbi porttitor', 531);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (122, '2025-09-04', 4, 'vel sem', 327);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (123, '2026-04-07', 1, 'justo in blandit ultrices', 257);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (124, '2025-12-22', 5, 'fusce consequat nulla nisl', 569);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (125, '2025-09-23', 5, 'amet eleifend', 346);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (126, '2025-11-04', 5, 'dictumst etiam faucibus', 133);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (127, '2026-03-16', 1, 'sapien cursus vestibulum proin', 219);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (128, '2026-03-05', 2, 'ante vel ipsum praesent blandit', 365);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (129, '2025-11-10', 2, 'dictumst etiam faucibus cursus', 408);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (130, '2025-12-18', 3, 'sapien cursus', 308);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (131, '2025-11-23', 1, 'purus phasellus', 564);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (132, '2026-03-09', 5, 'a odio', 135);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (133, '2025-12-24', 3, 'nibh ligula nec sem duis', 317);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (134, '2026-03-31', 1, 'nulla suscipit', 141);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (135, '2025-10-05', 4, 'nam tristique tortor', 592);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (136, '2025-12-02', 2, 'ante ipsum', 397);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (137, '2026-01-08', 2, 'morbi porttitor lorem id', 439);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (138, '2025-09-26', 4, 'ac nibh', 228);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (139, '2025-11-26', 1, 'ut massa volutpat convallis morbi', 343);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (140, '2025-08-24', 4, 'sed nisl nunc rhoncus dui', 553);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (141, '2025-10-10', 3, 'ante vivamus tortor duis', 183);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (142, '2026-03-27', 4, 'amet cursus id turpis integer', 417);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (143, '2026-03-04', 4, 'sapien iaculis congue vivamus', 540);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (144, '2025-12-30', 3, 'vel pede morbi porttitor lorem', 358);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (145, '2026-02-20', 5, 'in porttitor pede justo', 448);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (146, '2026-04-01', 5, 'gravida sem', 492);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (147, '2026-01-31', 4, 'nulla tellus in', 477);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (148, '2026-01-06', 4, 'sapien cursus', 520);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (149, '2026-01-16', 4, 'imperdiet nullam', 213);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (150, '2026-02-05', 4, 'tempus semper est quam', 223);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (151, '2026-03-15', 1, 'commodo placerat', 364);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (152, '2026-01-26', 5, 'in libero', 108);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (153, '2026-03-23', 4, 'consequat lectus in est risus', 465);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (154, '2025-12-17', 4, 'in hac habitasse platea', 246);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (155, '2026-03-01', 2, 'lacus at turpis donec', 263);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (156, '2025-12-22', 3, 'consequat ut', 139);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (157, '2026-03-12', 3, 'fermentum justo nec condimentum neque', 257);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (158, '2026-03-26', 5, 'posuere cubilia', 296);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (159, '2025-10-07', 2, 'cras non', 328);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (160, '2025-08-28', 3, 'eget orci vehicula', 335);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (161, '2025-10-27', 1, 'natoque penatibus et magnis dis', 178);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (162, '2025-09-12', 5, 'lectus aliquam sit amet', 545);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (163, '2025-11-25', 4, 'erat id mauris vulputate', 442);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (164, '2026-02-19', 4, 'lectus pellentesque', 145);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (165, '2026-03-14', 5, 'consequat ut', 103);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (166, '2026-02-14', 1, 'velit eu est congue elementum', 167);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (167, '2026-03-29', 5, 'sollicitudin mi sit', 575);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (168, '2025-09-13', 3, 'turpis adipiscing lorem vitae', 179);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (169, '2025-10-24', 1, 'tincidunt eu felis fusce', 151);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (170, '2025-10-27', 3, 'lacus morbi sem mauris laoreet', 402);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (171, '2025-10-28', 5, 'eget massa', 532);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (172, '2025-09-13', 2, 'in eleifend quam', 181);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (173, '2025-08-17', 4, 'vestibulum ante', 521);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (174, '2025-10-27', 3, 'leo pellentesque ultrices mattis odio', 326);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (175, '2026-04-04', 2, 'justo morbi', 288);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (176, '2025-08-21', 4, 'hendrerit at vulputate vitae nisl', 249);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (177, '2025-08-13', 1, 'mi integer', 593);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (178, '2025-10-25', 3, 'vulputate justo in blandit ultrices', 442);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (179, '2025-11-22', 4, 'at feugiat non pretium', 122);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (180, '2025-08-28', 5, 'massa tempor convallis', 376);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (181, '2026-04-06', 1, 'metus sapien ut nunc vestibulum', 347);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (182, '2025-09-03', 5, 'eu tincidunt in', 375);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (183, '2025-12-03', 2, 'vel pede morbi', 137);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (184, '2025-11-27', 5, 'pede ac diam cras pellentesque', 405);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (185, '2026-02-03', 4, 'in magna bibendum', 494);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (186, '2025-11-26', 5, 'ligula in lacus curabitur', 197);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (187, '2026-01-13', 2, 'nunc rhoncus', 280);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (188, '2026-03-26', 3, 'fusce posuere felis sed lacus', 339);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (189, '2025-11-03', 4, 'ridiculus mus vivamus vestibulum sagittis', 404);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (190, '2025-12-16', 5, 'rutrum rutrum neque', 180);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (191, '2026-01-22', 1, 'vehicula consequat morbi a', 192);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (192, '2025-11-14', 4, 'felis donec', 185);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (193, '2026-01-24', 1, 'odio odio elementum eu interdum', 469);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (194, '2026-03-02', 1, 'in consequat', 339);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (195, '2026-03-01', 5, 'sapien arcu sed augue aliquam', 198);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (196, '2026-01-01', 4, 'ut erat', 167);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (197, '2026-02-02', 3, 'aliquam lacus morbi', 153);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (198, '2026-02-18', 5, 'egestas metus aenean', 393);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (199, '2026-01-03', 3, 'amet erat nulla tempus', 344);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (200, '2026-02-06', 3, 'placerat ante nulla justo aliquam', 159);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (201, '2025-10-25', 2, 'at ipsum ac tellus semper', 218);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (202, '2025-10-12', 4, 'aliquam erat volutpat', 317);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (203, '2026-03-29', 1, 'massa id lobortis convallis tortor', 130);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (204, '2026-04-07', 1, 'imperdiet et', 151);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (205, '2025-10-06', 5, 'turpis nec euismod scelerisque', 328);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (206, '2025-10-19', 5, 'ligula vehicula consequat', 179);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (207, '2026-01-19', 4, 'eget semper rutrum', 459);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (208, '2026-02-28', 3, 'erat eros', 128);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (209, '2025-11-16', 1, 'lectus pellentesque at nulla', 211);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (210, '2026-04-03', 3, 'augue vel accumsan tellus nisi', 463);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (211, '2025-10-25', 4, 'pretium iaculis diam erat', 328);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (212, '2026-02-24', 1, 'felis fusce', 585);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (213, '2026-03-26', 1, 'sit amet nunc', 238);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (214, '2025-09-23', 5, 'nascetur ridiculus mus vivamus vestibulum', 164);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (215, '2025-11-23', 5, 'nunc nisl duis', 570);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (216, '2025-09-30', 1, 'eget elit sodales scelerisque', 175);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (217, '2025-09-21', 2, 'ridiculus mus vivamus', 278);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (218, '2025-11-06', 1, 'donec ut dolor morbi vel', 265);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (219, '2025-11-29', 2, 'vestibulum velit', 588);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (220, '2026-02-04', 2, 'orci mauris lacinia sapien', 509);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (221, '2025-10-30', 4, 'interdum mauris non', 497);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (222, '2026-01-13', 1, 'quis turpis eget elit', 497);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (223, '2026-02-06', 5, 'nec molestie sed', 441);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (224, '2025-08-13', 3, 'nisi eu orci mauris', 167);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (225, '2026-01-05', 1, 'cum sociis natoque penatibus et', 322);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (226, '2025-10-25', 2, 'sollicitudin vitae consectetuer eget', 448);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (227, '2025-12-07', 4, 'ipsum dolor sit amet', 491);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (228, '2025-11-09', 1, 'nulla eget', 374);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (229, '2026-01-24', 1, 'convallis tortor risus dapibus', 355);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (230, '2025-12-23', 4, 'amet lobortis sapien sapien non', 369);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (231, '2026-03-24', 5, 'vestibulum aliquet ultrices erat tortor', 109);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (232, '2025-11-02', 5, 'lacinia sapien quis libero nullam', 127);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (233, '2025-09-28', 4, 'odio in hac habitasse platea', 167);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (234, '2026-02-03', 1, 'bibendum imperdiet nullam orci pede', 105);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (235, '2025-12-04', 3, 'nisi nam ultrices libero non', 147);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (236, '2025-10-06', 2, 'pede libero quis', 102);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (237, '2026-03-31', 2, 'pede libero quis', 552);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (238, '2026-02-06', 5, 'sapien iaculis congue', 536);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (239, '2025-10-11', 4, 'sociis natoque', 376);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (240, '2025-09-08', 4, 'a nibh in quis', 363);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (241, '2026-02-04', 3, 'dolor morbi vel lectus in', 593);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (242, '2025-11-21', 1, 'mi in porttitor pede', 212);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (243, '2025-10-16', 5, 'viverra eget congue eget semper', 173);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (244, '2025-08-13', 1, 'bibendum morbi non quam', 345);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (245, '2026-03-06', 4, 'hac habitasse platea dictumst maecenas', 507);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (246, '2025-09-24', 2, 'mi sit', 335);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (247, '2026-04-06', 1, 'ante ipsum', 256);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (248, '2025-10-28', 4, 'nulla ac enim in', 125);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (249, '2025-08-17', 1, 'purus eu magna vulputate', 427);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (250, '2025-09-19', 1, 'suscipit nulla elit ac', 308);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (251, '2025-08-30', 5, 'mi in porttitor', 222);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (252, '2026-02-08', 2, 'pulvinar sed nisl', 436);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (253, '2025-09-30', 4, 'vestibulum ante', 155);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (254, '2026-03-21', 4, 'et ultrices posuere cubilia curae', 445);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (255, '2025-10-04', 4, 'amet nunc', 315);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (256, '2026-04-04', 1, 'adipiscing molestie hendrerit at', 457);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (257, '2026-01-29', 1, 'tellus semper interdum mauris', 139);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (258, '2025-08-17', 5, 'quisque porta volutpat erat', 115);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (259, '2025-11-18', 3, 'nam ultrices libero non', 448);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (260, '2025-08-20', 1, 'in lectus pellentesque at nulla', 446);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (261, '2025-10-12', 1, 'odio cras', 418);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (262, '2026-01-22', 1, 'ligula suspendisse ornare consequat lectus', 177);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (263, '2025-11-04', 4, 'interdum in ante', 354);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (264, '2026-03-12', 5, 'purus sit', 388);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (265, '2026-03-07', 1, 'morbi odio odio elementum', 273);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (266, '2025-08-31', 4, 'nulla mollis', 208);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (267, '2026-02-27', 2, 'pellentesque at nulla suspendisse potenti', 291);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (268, '2025-10-11', 3, 'ipsum praesent', 129);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (269, '2026-01-05', 2, 'vel augue vestibulum rutrum', 231);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (270, '2026-04-05', 2, 'curae duis faucibus', 243);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (271, '2025-10-30', 3, 'lacinia erat vestibulum sed magna', 134);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (272, '2025-09-05', 5, 'venenatis tristique', 492);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (273, '2025-08-31', 3, 'sociis natoque penatibus et magnis', 355);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (274, '2026-03-18', 3, 'at turpis donec posuere metus', 462);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (275, '2026-04-01', 3, 'pretium iaculis diam erat fermentum', 423);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (276, '2025-09-20', 3, 'viverra diam vitae quam', 415);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (277, '2026-01-25', 1, 'elementum ligula', 222);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (278, '2025-10-13', 2, 'lorem id', 194);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (279, '2026-01-06', 1, 'nascetur ridiculus', 512);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (280, '2026-01-28', 4, 'rutrum nulla nunc purus phasellus', 461);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (281, '2025-09-13', 3, 'odio justo', 264);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (282, '2026-01-16', 2, 'lorem vitae mattis', 299);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (283, '2025-09-26', 3, 'mattis odio donec vitae nisi', 243);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (284, '2026-01-14', 4, 'sed nisl', 231);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (285, '2026-03-29', 1, 'quis augue luctus', 448);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (286, '2026-03-20', 3, 'id pretium', 466);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (287, '2025-11-20', 1, 'magna bibendum imperdiet', 203);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (288, '2026-01-17', 3, 'dapibus duis at velit eu', 148);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (289, '2025-10-25', 2, 'laoreet ut', 246);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (290, '2025-08-27', 2, 'ut at dolor', 536);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (291, '2026-02-25', 1, 'viverra eget congue', 587);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (292, '2025-11-15', 2, 'nulla dapibus dolor vel', 499);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (293, '2025-09-26', 2, 'convallis morbi odio odio', 551);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (294, '2025-09-21', 1, 'iaculis congue vivamus metus', 162);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (295, '2025-10-05', 4, 'et magnis dis parturient', 358);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (296, '2025-09-11', 4, 'in lacus curabitur at ipsum', 451);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (297, '2025-11-21', 5, 'sit amet consectetuer adipiscing', 548);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (298, '2026-03-17', 3, 'blandit lacinia erat vestibulum', 261);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (299, '2025-09-20', 4, 'pellentesque viverra pede ac', 267);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (300, '2026-02-05', 3, 'mauris morbi non lectus aliquam', 420);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (301, '2025-09-20', 4, 'dictumst etiam faucibus', 138);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (302, '2026-03-21', 4, 'duis mattis egestas metus', 401);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (303, '2025-09-06', 5, 'vel ipsum praesent blandit', 531);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (304, '2026-01-21', 3, 'cras non velit nec', 379);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (305, '2025-10-30', 1, 'lorem vitae mattis nibh', 371);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (306, '2025-12-04', 2, 'fermentum justo nec condimentum', 384);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (307, '2025-12-04', 2, 'non ligula pellentesque ultrices phasellus', 441);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (308, '2025-11-17', 5, 'sem mauris laoreet ut', 212);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (309, '2026-03-21', 3, 'ultricies eu nibh quisque id', 478);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (310, '2025-11-15', 2, 'nulla facilisi cras non', 462);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (311, '2026-02-05', 1, 'justo nec', 514);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (312, '2025-09-27', 2, 'luctus tincidunt', 501);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (313, '2025-09-01', 2, 'vitae nisi nam ultrices libero', 191);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (314, '2025-10-21', 2, 'at velit eu', 586);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (315, '2026-02-07', 3, 'ut erat', 394);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (316, '2025-09-06', 5, 'pellentesque at nulla suspendisse potenti', 321);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (317, '2025-09-28', 4, 'venenatis tristique', 440);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (318, '2026-01-16', 4, 'vel nulla eget eros', 446);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (319, '2025-08-23', 5, 'amet erat nulla', 375);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (320, '2026-01-01', 4, 'ante ipsum primis in faucibus', 208);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (321, '2026-01-10', 5, 'molestie sed justo pellentesque viverra', 197);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (322, '2025-09-29', 1, 'in hac habitasse platea', 538);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (323, '2026-03-22', 4, 'magnis dis parturient', 242);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (324, '2025-09-24', 5, 'duis bibendum felis', 149);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (325, '2025-09-07', 3, 'mus etiam vel', 447);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (326, '2025-10-24', 1, 'lectus pellentesque at nulla', 282);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (327, '2026-03-04', 1, 'proin risus praesent lectus vestibulum', 278);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (328, '2025-12-07', 2, 'semper est quam', 301);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (329, '2026-04-06', 4, 'eu felis fusce posuere felis', 585);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (330, '2026-02-24', 5, 'odio donec vitae nisi', 197);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (331, '2025-10-17', 5, 'nunc nisl duis bibendum', 525);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (332, '2026-01-14', 2, 'non pretium quis lectus', 171);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (333, '2025-12-01', 3, 'morbi vel lectus', 477);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (334, '2026-01-14', 3, 'vel est', 268);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (335, '2025-10-09', 4, 'adipiscing elit', 573);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (336, '2025-08-31', 1, 'primis in', 112);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (337, '2026-03-25', 1, 'eget tempus', 555);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (338, '2026-01-18', 2, 'orci luctus', 425);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (339, '2025-10-01', 1, 'ligula suspendisse ornare consequat', 322);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (340, '2026-03-18', 4, 'at nunc commodo placerat praesent', 553);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (341, '2025-09-28', 1, 'eu mi nulla', 566);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (342, '2026-02-10', 5, 'quis augue luctus tincidunt', 198);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (343, '2025-11-23', 3, 'in lectus', 222);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (344, '2025-08-20', 2, 'cras pellentesque volutpat dui maecenas', 585);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (345, '2025-12-14', 5, 'suscipit a', 541);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (346, '2026-01-16', 4, 'ipsum integer a', 511);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (347, '2025-10-23', 2, 'ipsum primis in faucibus', 343);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (348, '2025-10-18', 1, 'nibh fusce lacus purus aliquet', 418);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (349, '2025-11-02', 5, 'faucibus orci luctus et', 215);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (350, '2026-01-24', 3, 'posuere cubilia curae duis', 320);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (351, '2025-09-24', 5, 'augue vestibulum', 597);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (352, '2026-02-26', 2, 'odio justo sollicitudin', 183);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (353, '2025-12-17', 2, 'lacinia nisi', 356);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (354, '2026-01-19', 1, 'mus etiam vel augue vestibulum', 465);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (355, '2025-09-25', 1, 'ut odio cras mi', 215);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (356, '2025-09-05', 3, 'mollis molestie lorem quisque', 260);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (357, '2025-11-09', 3, 'mauris sit amet eros suspendisse', 275);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (358, '2025-11-10', 3, 'in purus eu', 376);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (359, '2026-02-24', 4, 'lorem vitae mattis', 468);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (360, '2026-01-23', 1, 'vulputate nonummy maecenas tincidunt lacus', 402);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (361, '2025-08-31', 5, 'sit amet lobortis', 420);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (362, '2026-01-07', 3, 'id massa id nisl venenatis', 577);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (363, '2025-11-15', 2, 'a nibh', 506);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (364, '2026-03-15', 4, 'neque sapien placerat', 137);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (365, '2026-03-06', 1, 'et ultrices posuere cubilia', 459);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (366, '2025-12-10', 1, 'consequat lectus in est risus', 449);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (367, '2026-03-01', 5, 'maecenas rhoncus aliquam lacus morbi', 482);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (368, '2026-01-13', 4, 'integer ac leo', 146);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (369, '2026-01-04', 2, 'integer a nibh', 366);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (370, '2026-02-17', 5, 'non interdum in ante vestibulum', 331);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (371, '2025-11-19', 1, 'odio elementum eu interdum eu', 358);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (372, '2025-11-10', 3, 'fringilla rhoncus mauris', 585);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (373, '2025-12-17', 3, 'dolor sit amet consectetuer adipiscing', 169);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (374, '2025-10-06', 5, 'suscipit a', 447);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (375, '2026-01-03', 5, 'justo aliquam quis turpis', 279);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (376, '2025-11-30', 5, 'at dolor quis', 390);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (377, '2026-02-01', 3, 'diam erat fermentum', 334);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (378, '2025-10-06', 1, 'ipsum aliquam', 140);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (379, '2026-01-09', 5, 'sapien sapien', 434);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (380, '2026-01-30', 5, 'sit amet nulla quisque', 283);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (381, '2025-10-19', 5, 'ligula suspendisse ornare consequat', 172);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (382, '2026-01-14', 2, 'rutrum nulla tellus', 244);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (383, '2025-11-06', 3, 'dui vel', 467);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (384, '2025-12-10', 2, 'sit amet consectetuer adipiscing', 431);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (385, '2025-11-29', 5, 'integer non velit donec diam', 461);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (386, '2026-03-16', 4, 'donec pharetra magna', 504);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (387, '2025-11-13', 4, 'integer non velit donec diam', 298);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (388, '2025-10-29', 1, 'faucibus orci luctus et', 111);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (389, '2026-03-13', 2, 'quisque arcu libero rutrum ac', 145);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (390, '2025-11-12', 4, 'aenean lectus pellentesque eget nunc', 112);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (391, '2025-08-14', 1, 'massa id', 381);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (392, '2026-01-15', 2, 'ac neque', 337);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (393, '2025-10-01', 5, 'sit amet diam in magna', 115);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (394, '2025-09-05', 2, 'maecenas rhoncus', 311);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (395, '2026-02-04', 2, 'non interdum in ante vestibulum', 351);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (396, '2025-11-13', 4, 'sit amet justo morbi ut', 534);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (397, '2026-02-18', 2, 'felis sed lacus', 505);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (398, '2026-01-24', 4, 'justo nec', 173);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (399, '2026-03-29', 1, 'id mauris vulputate', 427);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (400, '2026-03-03', 4, 'nunc donec quis orci eget', 375);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (401, '2025-10-12', 3, 'lacinia nisi', 456);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (402, '2025-09-25', 5, 'lacus morbi quis tortor', 191);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (403, '2025-08-17', 4, 'lobortis sapien', 239);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (404, '2026-01-18', 3, 'dui nec', 513);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (405, '2025-08-27', 4, 'a ipsum integer a', 501);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (406, '2025-10-18', 3, 'pulvinar sed', 407);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (407, '2026-02-08', 3, 'posuere felis sed lacus', 251);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (408, '2025-12-20', 1, 'nulla tellus in', 233);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (409, '2026-01-25', 2, 'sagittis dui vel nisl duis', 333);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (410, '2025-10-31', 4, 'tortor sollicitudin mi sit amet', 445);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (411, '2026-02-25', 3, 'morbi porttitor lorem id ligula', 170);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (412, '2026-02-05', 3, 'est donec odio justo sollicitudin', 387);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (413, '2026-01-20', 3, 'tellus in sagittis', 451);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (414, '2026-02-27', 5, 'sed lacus morbi sem mauris', 335);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (415, '2025-10-12', 3, 'diam neque vestibulum', 354);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (416, '2025-11-16', 5, 'convallis nulla', 249);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (417, '2025-10-07', 3, 'amet nunc viverra', 511);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (418, '2026-03-04', 4, 'est risus auctor sed tristique', 439);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (419, '2026-01-28', 5, 'congue diam id ornare', 337);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (420, '2025-12-14', 5, 'est risus', 138);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (421, '2025-12-12', 2, 'blandit non interdum in', 429);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (422, '2025-09-20', 5, 'duis consequat dui nec', 254);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (423, '2026-03-29', 2, 'posuere cubilia curae nulla dapibus', 415);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (424, '2025-09-01', 2, 'praesent blandit', 456);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (425, '2026-01-28', 1, 'tortor sollicitudin mi', 126);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (426, '2025-10-06', 4, 'cubilia curae', 384);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (427, '2025-09-21', 3, 'vivamus in', 425);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (428, '2026-01-20', 3, 'congue diam id', 415);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (429, '2025-08-28', 1, 'blandit mi in porttitor pede', 527);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (430, '2025-09-12', 3, 'mauris non ligula pellentesque', 175);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (431, '2025-11-15', 1, 'amet consectetuer adipiscing', 469);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (432, '2026-02-05', 3, 'nascetur ridiculus mus', 327);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (433, '2026-02-15', 3, 'congue etiam justo etiam', 563);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (434, '2026-03-02', 4, 'convallis eget eleifend', 314);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (435, '2025-10-21', 2, 'primis in faucibus orci', 431);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (436, '2025-09-01', 2, 'sed lacus', 334);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (437, '2025-09-24', 4, 'etiam vel', 573);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (438, '2026-03-15', 4, 'mattis pulvinar nulla', 422);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (439, '2026-03-11', 1, 'quam pede lobortis', 231);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (440, '2026-03-28', 5, 'et tempus', 595);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (441, '2025-11-02', 3, 'eu felis fusce', 149);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (442, '2025-10-27', 3, 'viverra diam vitae', 179);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (443, '2025-12-07', 1, 'tincidunt eu felis fusce', 558);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (444, '2025-12-27', 4, 'ultrices posuere cubilia curae', 403);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (445, '2025-10-21', 2, 'in congue', 319);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (446, '2026-01-11', 5, 'ultrices posuere cubilia', 331);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (447, '2026-03-29', 4, 'in blandit ultrices enim lorem', 324);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (448, '2025-08-17', 3, 'turpis a pede posuere', 174);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (449, '2026-02-03', 4, 'ultrices posuere cubilia', 375);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (450, '2025-09-20', 1, 'aliquam lacus', 573);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (451, '2026-01-26', 4, 'pretium nisl ut volutpat', 385);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (452, '2025-08-21', 4, 'lacinia sapien quis libero nullam', 368);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (453, '2025-12-22', 2, 'tristique tortor eu', 538);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (454, '2026-01-03', 1, 'fusce posuere', 147);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (455, '2025-11-29', 4, 'tortor quis', 322);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (456, '2025-11-17', 3, 'primis in faucibus orci luctus', 344);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (457, '2026-01-06', 5, 'suspendisse accumsan tortor', 107);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (458, '2025-09-02', 4, 'tempus sit amet', 270);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (459, '2025-11-10', 3, 'nunc viverra dapibus nulla suscipit', 593);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (460, '2025-10-13', 5, 'vulputate justo in blandit ultrices', 109);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (461, '2025-10-15', 1, 'metus vitae', 144);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (462, '2026-03-24', 1, 'mi pede malesuada', 264);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (463, '2025-12-26', 2, 'duis consequat', 250);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (464, '2025-12-29', 2, 'tempus vel', 293);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (465, '2025-09-27', 2, 'consequat nulla', 305);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (466, '2025-10-15', 1, 'lorem vitae', 217);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (467, '2025-12-26', 1, 'proin risus praesent lectus', 104);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (468, '2026-04-08', 5, 'vestibulum sit amet cursus id', 479);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (469, '2025-11-02', 3, 'in felis donec semper', 575);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (470, '2026-03-17', 2, 'a feugiat', 240);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (471, '2025-09-16', 4, 'cubilia curae mauris viverra diam', 572);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (472, '2025-11-13', 4, 'sapien cum sociis', 236);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (473, '2026-02-16', 5, 'ultrices posuere', 411);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (474, '2025-11-04', 2, 'morbi non quam', 551);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (475, '2025-08-20', 3, 'in hac', 227);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (476, '2025-10-21', 2, 'orci eget orci', 297);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (477, '2026-03-27', 5, 'cum sociis natoque penatibus et', 454);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (478, '2026-03-27', 1, 'luctus ultricies eu nibh', 392);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (479, '2026-03-31', 3, 'porttitor pede justo', 397);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (480, '2025-10-29', 3, 'duis consequat', 297);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (481, '2026-02-28', 4, 'et ultrices posuere cubilia', 344);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (482, '2026-03-21', 5, 'vel ipsum praesent', 228);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (483, '2025-12-11', 5, 'viverra pede', 338);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (484, '2026-01-21', 2, 'nec nisi volutpat eleifend', 105);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (485, '2025-10-04', 4, 'vel est', 293);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (486, '2025-09-29', 2, 'vestibulum vestibulum ante', 411);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (487, '2025-11-15', 4, 'ut suscipit a', 158);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (488, '2025-10-14', 4, 'volutpat erat quisque', 226);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (489, '2026-01-27', 2, 'integer ac neque duis bibendum', 214);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (490, '2025-11-23', 2, 'sed tincidunt eu felis fusce', 138);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (491, '2026-02-25', 2, 'dolor vel', 274);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (492, '2025-12-25', 4, 'vestibulum quam sapien', 249);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (493, '2026-01-11', 5, 'malesuada in imperdiet et', 307);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (494, '2026-02-20', 3, 'arcu sed augue', 329);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (495, '2025-09-01', 3, 'cum sociis natoque', 411);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (496, '2025-11-29', 4, 'morbi odio odio', 209);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (497, '2026-01-15', 5, 'vitae ipsum aliquam', 122);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (498, '2026-03-13', 2, 'in lacus curabitur', 570);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (499, '2026-02-05', 4, 'proin at turpis a pede', 265);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (500, '2026-01-15', 2, 'viverra eget congue eget', 148);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (501, '2025-12-17', 1, 'vestibulum velit', 490);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (502, '2025-09-15', 3, 'consectetuer adipiscing', 102);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (503, '2026-04-07', 1, 'sed interdum venenatis', 532);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (504, '2025-12-10', 4, 'aenean auctor gravida', 276);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (505, '2025-09-11', 1, 'purus eu magna', 233);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (506, '2025-10-17', 2, 'faucibus orci luctus et ultrices', 544);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (507, '2025-09-27', 1, 'nulla sed', 226);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (508, '2026-02-19', 4, 'convallis duis consequat', 322);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (509, '2025-10-17', 4, 'tincidunt nulla mollis molestie', 320);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (510, '2026-02-09', 3, 'nunc nisl duis bibendum', 591);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (511, '2025-09-29', 4, 'sit amet consectetuer adipiscing', 187);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (512, '2025-11-11', 3, 'mattis pulvinar nulla', 166);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (513, '2026-03-24', 3, 'platea dictumst maecenas ut', 385);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (514, '2025-10-21', 3, 'erat volutpat in congue etiam', 464);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (515, '2025-12-09', 5, 'leo odio condimentum id', 343);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (516, '2026-02-11', 4, 'quam fringilla rhoncus mauris enim', 361);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (517, '2025-11-26', 2, 'arcu sed augue aliquam erat', 359);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (518, '2025-08-13', 5, 'interdum mauris', 125);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (519, '2026-03-11', 4, 'ut tellus nulla ut', 426);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (520, '2025-08-12', 5, 'neque vestibulum', 166);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (521, '2025-08-25', 4, 'ut at dolor', 326);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (522, '2025-11-28', 5, 'suspendisse potenti cras in', 251);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (523, '2026-04-05', 1, 'in leo', 283);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (524, '2025-11-16', 2, 'massa tempor convallis nulla neque', 362);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (525, '2025-09-02', 1, 'sapien quis libero', 193);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (526, '2025-11-07', 3, 'leo pellentesque ultrices', 577);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (527, '2025-08-14', 5, 'habitasse platea', 104);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (528, '2025-10-04', 3, 'consequat in consequat ut', 369);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (529, '2025-12-21', 4, 'duis at', 576);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (530, '2026-03-07', 3, 'ipsum aliquam', 331);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (531, '2026-01-26', 5, 'mus vivamus vestibulum sagittis', 124);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (532, '2026-01-06', 2, 'phasellus id', 546);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (533, '2026-02-01', 5, 'justo sit amet sapien dignissim', 155);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (534, '2026-02-17', 3, 'enim leo rhoncus sed vestibulum', 543);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (535, '2025-12-01', 2, 'ultrices posuere', 332);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (536, '2026-01-14', 4, 'laoreet ut rhoncus', 240);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (537, '2025-12-08', 1, 'vulputate vitae nisl aenean', 295);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (538, '2025-11-01', 2, 'nulla suspendisse', 467);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (539, '2025-11-26', 3, 'nascetur ridiculus mus vivamus vestibulum', 420);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (540, '2025-09-06', 5, 'at dolor quis odio consequat', 403);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (541, '2026-03-07', 3, 'mi pede malesuada', 424);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (542, '2025-11-24', 4, 'vivamus vel nulla', 291);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (543, '2025-11-18', 3, 'leo pellentesque ultrices mattis odio', 116);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (544, '2025-08-14', 4, 'nam nulla integer pede justo', 589);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (545, '2025-09-25', 4, 'volutpat erat', 240);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (546, '2025-10-24', 3, 'ac nibh fusce lacus purus', 402);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (547, '2026-01-09', 4, 'sed sagittis nam', 470);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (548, '2026-01-25', 4, 'rutrum ac', 506);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (549, '2025-08-24', 5, 'sit amet consectetuer adipiscing elit', 275);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (550, '2025-12-11', 3, 'rutrum nulla nunc', 584);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (551, '2025-09-07', 4, 'tempor convallis', 401);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (552, '2025-08-22', 2, 'id mauris vulputate elementum', 428);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (553, '2025-11-01', 3, 'massa volutpat convallis', 539);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (554, '2026-03-23', 4, 'accumsan tortor', 584);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (555, '2026-01-04', 3, 'ac est', 265);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (556, '2025-08-27', 3, 'pede ac', 369);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (557, '2025-12-13', 3, 'bibendum imperdiet nullam orci pede', 410);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (558, '2025-11-25', 5, 'luctus cum', 164);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (559, '2026-02-21', 4, 'sed magna at nunc commodo', 327);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (560, '2026-03-23', 3, 'dis parturient montes nascetur ridiculus', 108);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (561, '2025-12-28', 2, 'varius integer ac leo pellentesque', 320);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (562, '2025-09-26', 4, 'diam in magna bibendum imperdiet', 550);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (563, '2025-10-26', 3, 'mauris vulputate elementum', 329);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (564, '2025-09-19', 3, 'sem duis', 463);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (565, '2025-10-14', 3, 'phasellus sit amet', 210);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (566, '2025-12-28', 5, 'nec euismod scelerisque', 517);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (567, '2026-02-22', 1, 'sollicitudin vitae', 528);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (568, '2025-09-15', 3, 'lobortis ligula sit amet', 440);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (569, '2025-11-05', 5, 'at velit vivamus', 210);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (570, '2025-10-10', 1, 'sapien in sapien', 559);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (571, '2025-11-10', 4, 'magna vestibulum', 435);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (572, '2025-10-03', 3, 'sapien iaculis congue vivamus', 342);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (573, '2026-02-09', 5, 'curabitur in libero ut massa', 377);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (574, '2026-02-08', 4, 'dui luctus', 142);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (575, '2025-10-18', 1, 'semper interdum', 411);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (576, '2025-10-24', 4, 'mi sit amet lobortis', 451);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (577, '2025-09-14', 2, 'justo in blandit', 294);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (578, '2025-08-31', 1, 'adipiscing lorem vitae', 329);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (579, '2026-03-20', 2, 'suspendisse potenti', 253);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (580, '2025-08-12', 3, 'dapibus at diam nam', 505);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (581, '2025-11-01', 1, 'sem sed sagittis nam congue', 117);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (582, '2025-09-28', 4, 'lobortis ligula sit amet eleifend', 465);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (583, '2025-10-21', 4, 'nam nulla', 406);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (584, '2026-01-17', 4, 'ac leo', 288);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (585, '2026-04-02', 5, 'dolor quis odio', 314);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (586, '2026-02-18', 2, 'eget eleifend', 152);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (587, '2025-10-19', 4, 'suscipit ligula in', 343);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (588, '2025-12-15', 5, 'at nibh in', 258);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (589, '2025-09-16', 1, 'nisl nunc nisl duis bibendum', 553);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (590, '2025-08-16', 4, 'luctus et', 491);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (591, '2026-01-05', 2, 'cubilia curae nulla dapibus', 184);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (592, '2025-09-04', 1, 'tempus vel pede morbi', 495);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (593, '2026-01-03', 1, 'ut massa quis', 428);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (594, '2026-03-02', 2, 'rhoncus aliquam lacus', 448);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (595, '2025-10-04', 4, 'mauris eget', 158);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (596, '2026-03-22', 5, 'blandit non interdum', 151);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (597, '2026-03-14', 5, 'blandit mi in porttitor pede', 404);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (598, '2026-01-23', 2, 'libero nam', 481);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (599, '2025-11-10', 4, 'non ligula', 468);
insert into FLIGHT_ALERTS (Alert_ID, Alert_Timestamp, Severity_Level, Alert_Message, Assignment_ID) values (600, '2025-09-28', 3, 'lacus morbi quis tortor', 290);
