insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (101, 'Food - Bakery', 31);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (102, 'Bicycles', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (103, 'Pets', 47);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (104, 'Clothing - Shoes', 88);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (105, 'Office', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (106, 'Food - Snacks', 66);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (107, 'Home', 88);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (108, 'Accessories', 7);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (109, 'Clothing - Accessories', 90);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (110, 'Food - Canned Goods', 77);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (111, 'Food - Snacks', 93);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (112, 'Outdoor', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (113, 'Food - Frozen Desserts', 93);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (114, 'Food - Snacks', 91);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (115, 'Home', 90);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (116, 'Clothing - Accessories', 17);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (117, 'Kitchen', 50);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (118, 'Food - Breakfast', 30);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (119, 'Electronics', 100);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (120, 'Pets', 78);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (121, 'Food - Grains', 81);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (122, 'Food - Canned Goods', 66);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (123, 'Clothing', 19);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (124, 'Food - Canned Goods', 47);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (125, 'Food - Household', 83);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (126, 'Beauty', 78);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (127, 'Home', 57);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (128, 'Health', 26);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (129, 'Food - Spices', 45);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (130, 'Food - Meat & Seafood', 86);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (131, 'Kitchen', 55);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (132, 'Home', 56);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (133, 'Accessories', 63);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (134, 'Food - Frozen Vegetables', 14);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (135, 'Food - Vegetables', 87);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (136, 'Food - Snacks', 26);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (137, 'Clothing - Bottoms', 55);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (138, 'Automotive', 24);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (139, 'Food - Canned Goods', 50);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (140, 'Food - Meat', 29);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (141, 'Clothing - Shoes', 68);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (142, 'Food - Snacks', 85);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (143, 'Food - Snacks', 85);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (144, 'Food - Sauces', 14);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (145, 'Photography', 74);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (146, 'Clothing - Outerwear', 9);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (147, 'Food - Dairy', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (148, 'Travel', 30);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (149, 'Food - Prepared Foods', 18);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (150, 'Fitness', 93);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (151, 'Electronics', 86);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (152, 'Food - Frozen Foods', 2);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (153, 'Food - Snacks', 97);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (154, 'Food - Prepared Foods', 35);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (155, 'Clothing - Outerwear', 14);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (156, 'Accessories', 67);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (157, 'Food - Produce', 83);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (158, 'Kitchen', 56);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (159, 'Toys', 73);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (160, 'Garden', 97);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (161, 'Food - Baking', 21);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (162, 'Photography', 13);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (163, 'Electronics', 8);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (164, 'Electronics', 81);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (165, 'Outdoor', 77);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (166, 'Food - Baking', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (167, 'Clothing - Dresses', 28);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (168, 'Food - Frozen Meals', 43);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (169, 'Clothing - Footwear', 84);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (170, 'Kitchen', 68);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (171, 'Food - Grains', 54);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (172, 'Clothing - Outerwear', 23);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (173, 'Food - Snacks', 48);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (174, 'Clothing - Shirts', 2);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (175, 'Pets', 81);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (176, 'Kitchen', 24);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (177, 'Electronics', 12);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (178, 'Food - Condiments', 100);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (179, 'Pets', 88);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (180, 'Toys', 6);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (181, 'Food - Dried Fruits', 71);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (182, 'Food - Frozen', 22);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (183, 'Electronics', 100);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (184, 'Food - Snacks', 99);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (185, 'Toys', 37);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (186, 'Food - Snacks', 4);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (187, 'Outdoor', 93);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (188, 'Food - Snacks', 24);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (189, 'Gaming', 41);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (190, 'Food - Beverages', 58);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (191, 'Garden', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (192, 'Food - Condiments', 93);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (193, 'Food - Frozen Desserts', 40);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (194, 'Clothing - Tops', 56);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (195, 'Food - Breakfast', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (196, 'Wearable Tech', 8);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (197, 'Computers', 80);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (198, 'Food - Canned Soups', 74);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (199, 'Kitchen', 10);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (200, 'Food - Prepared Meals', 57);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (201, 'Clothing - Footwear', 53);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (202, 'Food - Dried Fruits', 52);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (203, 'Kitchen', 44);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (204, 'Kitchen', 89);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (205, 'Health', 47);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (206, 'Food - Fruits', 56);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (207, 'Clothing - Activewear', 23);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (208, 'Food - Snacks', 33);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (209, 'Food - Baking', 29);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (210, 'Food - Pasta', 55);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (211, 'Food - Frozen Foods', 79);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (212, 'Accessories', 96);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (213, 'Food - Sauces', 22);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (214, 'Food - Protein', 98);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (215, 'Travel', 99);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (216, 'Outdoor', 10);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (217, 'Food - Snacks', 42);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (218, 'Home', 90);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (219, 'Food - Prepared Meals', 36);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (220, 'Food - Bakery', 60);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (221, 'Food - Soups', 19);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (222, 'Electronics', 46);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (223, 'Home', 64);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (224, 'Food - Prepared Foods', 47);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (225, 'Food - Dairy', 50);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (226, 'Food - Grains', 30);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (227, 'Audio', 76);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (228, 'Toys', 70);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (229, 'Outdoor', 41);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (230, 'Sports', 90);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (231, 'Accessories', 74);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (232, 'Fitness', 22);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (233, 'Clothing - Activewear', 60);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (234, 'Food - Snacks', 53);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (235, 'Food - Frozen Meals', 90);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (236, 'Food - Prepared Foods', 62);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (237, 'Health', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (238, 'Food - Frozen Foods', 36);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (239, 'Food - Snacks', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (240, 'Food - Bakery', 90);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (241, 'Outdoor', 23);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (242, 'Kitchen', 46);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (243, 'Clothing - Accessories', 62);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (244, 'Travel', 57);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (245, 'Kitchen', 80);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (246, 'Home', 29);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (247, 'Home', 94);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (248, 'Food - Deli Meats', 40);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (249, 'Garden', 9);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (250, 'Health', 42);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (251, 'Kitchen', 50);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (252, 'Food - Condiments', 67);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (253, 'Smart Home', 74);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (254, 'Clothing', 76);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (255, 'Food - Snacks', 6);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (256, 'Food - Cereals', 43);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (257, 'Outdoor', 61);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (258, 'Food - Snacks', 3);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (259, 'Food - Meat', 5);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (260, 'Beauty', 49);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (261, 'Fitness', 66);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (262, 'Garden', 60);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (263, 'Kitchen', 97);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (264, 'Health', 12);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (265, 'Safety', 100);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (266, 'Food - Dairy Alternatives', 17);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (267, 'Accessories', 59);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (268, 'Fitness', 19);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (269, 'Food - Baking', 86);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (270, 'Food - Soups', 86);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (271, 'Food - Snacks', 23);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (272, 'Food - Fresh Produce', 80);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (273, 'Food - Snacks', 74);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (274, 'Toys', 79);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (275, 'Food - Bakery', 73);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (276, 'Office', 53);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (277, 'Food - Snacks', 20);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (278, 'Clothing - Shirts', 23);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (279, 'Outdoor', 53);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (280, 'Food - Vegetables', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (281, 'Food - Frozen Foods', 61);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (282, 'Clothing - Dresses', 43);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (283, 'Books', 78);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (284, 'Kitchen', 56);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (285, 'Kitchen', 80);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (286, 'Food - Baked Goods', 50);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (287, 'Home', 3);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (288, 'Clothing - Accessories', 14);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (289, 'Audio', 18);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (290, 'Food - Snacks', 30);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (291, 'Outdoor', 45);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (292, 'Food - Dairy', 39);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (293, 'Food - Seafood', 90);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (294, 'Garden', 79);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (295, 'Outdoor', 54);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (296, 'Clothing - Coats', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (297, 'Home', 99);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (298, 'Food - Meats', 72);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (299, 'Pets', 24);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (300, 'Toys', 71);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (301, 'Food - Baking', 14);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (302, 'Food - Soups', 12);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (303, 'Accessories', 43);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (304, 'Food - Dressings', 36);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (305, 'Outdoor', 48);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (306, 'Wearable Tech', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (307, 'Food - Bakery', 4);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (308, 'Kitchen', 3);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (309, 'Food - Snacks', 3);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (310, 'Home', 5);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (311, 'Food - Snacks', 46);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (312, 'Health', 75);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (313, 'Health', 84);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (314, 'Food - Frozen Foods', 85);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (315, 'Kitchen', 10);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (316, 'Pets', 17);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (317, 'Food - Cooking Essentials', 35);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (318, 'Pets', 85);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (319, 'Beauty', 47);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (320, 'Food - Dairy Alternatives', 59);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (321, 'Audio', 15);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (322, 'Kitchen', 73);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (323, 'Food - Frozen', 97);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (324, 'Kitchen', 83);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (325, 'Kitchen', 19);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (326, 'Food - Baking', 35);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (327, 'Clothing - Bags', 28);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (328, 'Food - Condiments', 27);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (329, 'Fitness', 46);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (330, 'Toys', 73);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (331, 'Kitchen', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (332, 'Clothing - Dresses', 68);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (333, 'Food - Canned Goods', 41);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (334, 'Food - Condiments', 15);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (335, 'Outdoor', 85);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (336, 'Clothing - Accessories', 71);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (337, 'Kitchen', 58);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (338, 'Food - Canned Goods', 4);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (339, 'Outdoor', 55);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (340, 'Clothing - Bottoms', 95);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (341, 'Clothing - Tops', 10);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (342, 'Food - Cooking Kits', 94);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (343, 'Food - Frozen Foods', 52);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (344, 'Clothing - Tops', 69);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (345, 'Food - Bakery', 9);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (346, 'Accessories', 61);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (347, 'Home', 18);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (348, 'Garden', 26);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (349, 'Footwear', 33);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (350, 'Kitchen', 81);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (351, 'Home', 14);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (352, 'Kitchen', 61);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (353, 'Kitchen', 65);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (354, 'Clothing - Activewear', 30);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (355, 'Kitchen', 62);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (356, 'Food - Fresh Produce', 41);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (357, 'Food - Confectionery', 31);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (358, 'Food - Frozen Foods', 4);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (359, 'Pets', 28);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (360, 'Food - Frozen', 6);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (361, 'Food - Snacks', 47);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (362, 'Food - Frozen Foods', 18);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (363, 'Food - Snacks', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (364, 'Home', 34);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (365, 'Pets', 40);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (366, 'Home', 31);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (367, 'Home', 35);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (368, 'Food - Snacks', 94);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (369, 'Kitchen', 22);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (370, 'Clothing - Bottoms', 87);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (371, 'Automotive', 86);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (372, 'Home', 38);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (373, 'Food - Produce', 77);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (374, 'Food - Snacks', 12);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (375, 'Food - Breakfast', 72);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (376, 'Kitchen', 35);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (377, 'Outdoor', 99);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (378, 'Kitchen', 37);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (379, 'Electronics', 76);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (380, 'Food - Meats', 69);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (381, 'Food - Dairy Alternatives', 71);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (382, 'Food - Meat', 66);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (383, 'Pets', 48);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (384, 'Food - Frozen Meals', 8);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (385, 'Office', 45);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (386, 'Home Appliances', 10);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (387, 'Storage', 51);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (388, 'Food - Condiments', 10);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (389, 'Food - Bakery', 32);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (390, 'Pets', 26);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (391, 'Food - Baking Goods', 53);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (392, 'Food - Nuts', 18);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (393, 'Home', 42);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (394, 'Food - Breakfast', 68);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (395, 'Food - Frozen Meals', 1);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (396, 'Food - Snacks', 36);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (397, 'Kitchen', 5);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (398, 'Clothing - Tops', 35);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (399, 'Food - Frozen Vegetables', 42);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (400, 'Automotive', 73);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (401, 'Food - Beverages', 32);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (402, 'Food - Dried Fruits', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (403, 'Food - Frozen Food', 67);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (404, 'Clothing - Loungewear', 10);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (405, 'Food - Condiments', 53);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (406, 'Food - Bakery', 14);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (407, 'Clothing - Jumpsuits', 80);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (408, 'Food - Snacks', 66);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (409, 'Food - Dressing', 74);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (410, 'Health', 19);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (411, 'Food - Dairy', 49);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (412, 'Food - Spices', 50);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (413, 'Clothing - Outerwear', 49);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (414, 'Office', 8);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (415, 'Food - Dairy Alternatives', 8);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (416, 'Tools', 90);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (417, 'Kitchen', 99);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (418, 'Food - Sides', 60);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (419, 'Food - Grains', 97);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (420, 'Fitness', 53);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (421, 'Outdoor', 69);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (422, 'Food - Meat', 79);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (423, 'Kitchen', 69);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (424, 'Home Appliances', 77);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (425, 'Food - Salads', 55);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (426, 'Home', 2);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (427, 'Food - Dairy Alternatives', 55);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (428, 'Kitchen', 64);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (429, 'Home', 96);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (430, 'Food - Pasta', 57);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (431, 'Food - Beverages', 82);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (432, 'Outdoor', 24);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (433, 'Food - Snacks', 14);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (434, 'Food - Produce', 59);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (435, 'Garden', 46);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (436, 'Home', 41);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (437, 'Electronics', 76);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (438, 'Fitness', 22);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (439, 'Food - Dried Fruits', 87);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (440, 'Food - Produce', 88);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (441, 'Kitchen', 43);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (442, 'Food - Beverages', 9);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (443, 'Food - Produce', 53);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (444, 'Office', 29);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (445, 'Food', 55);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (446, 'Food - Frozen Vegetables', 12);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (447, 'Sports', 35);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (448, 'Outdoor', 5);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (449, 'Books', 42);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (450, 'Food - Snacks', 18);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (451, 'Food - Breakfast', 48);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (452, 'Food - Fruits', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (453, 'Kitchen', 21);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (454, 'Garden', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (455, 'Garden', 59);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (456, 'Fitness', 20);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (457, 'Food - Condiments', 83);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (458, 'Food - Beverages', 75);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (459, 'Electronics', 65);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (460, 'Garden', 48);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (461, 'Art Supplies', 37);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (462, 'Accessories', 15);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (463, 'Food - Frozen Foods', 82);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (464, 'Travel', 66);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (465, 'Food - Vegetables', 97);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (466, 'Electronics', 96);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (467, 'Kitchen', 74);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (468, 'Kitchen', 40);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (469, 'Home', 19);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (470, 'Office', 75);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (471, 'Outdoor', 38);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (472, 'Food - Canned Goods', 58);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (473, 'Food - Frozen Foods', 42);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (474, 'Kitchen', 30);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (475, 'Food - Grains', 16);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (476, 'Fitness', 45);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (477, 'Accessories', 5);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (478, 'Food - Condiments', 42);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (479, 'Fitness', 71);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (480, 'Pets', 99);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (481, 'Kitchen', 56);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (482, 'Food - Bakery', 84);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (483, 'Food - Freezer', 78);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (484, 'Electronics', 76);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (485, 'Food - Baking', 98);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (486, 'Food - Bakery', 97);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (487, 'Clothing - Tops', 83);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (488, 'Clothing - Tops', 60);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (489, 'Books', 70);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (490, 'Food - Fruits', 21);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (491, 'Food - Condiments', 12);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (492, 'Home', 62);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (493, 'Food - Grains', 62);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (494, 'Home Improvement', 82);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (495, 'Pets', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (496, 'Food - Condiments', 57);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (497, 'Clothing - Accessories', 96);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (498, 'Food - Condiments', 100);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (499, 'Gaming', 85);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (500, 'Food - Bakery', 69);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (501, 'Food - Meat', 95);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (502, 'Clothing - Shirts', 18);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (503, 'Food - Produce', 19);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (504, 'Food - Beverages', 70);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (505, 'Food - Grains', 52);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (506, 'Outdoor', 41);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (507, 'Food - Frozen Foods', 83);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (508, 'Food - Frozen Foods', 58);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (509, 'Books', 13);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (510, 'Home', 84);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (511, 'Food - Desserts', 93);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (512, 'Food - Dairy', 68);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (513, 'Food - Beverages', 26);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (514, 'Food - Meat', 15);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (515, 'Food - Frozen', 64);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (516, 'Food - Baking', 1);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (517, 'Food - Prepared Foods', 26);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (518, 'Food - Condiments', 17);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (519, 'Food - Beverages', 2);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (520, 'Fitness', 81);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (521, 'Food - Snacks', 59);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (522, 'Clothing - Tops', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (523, 'Clothing - Footwear', 42);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (524, 'Fitness', 4);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (525, 'Food - Breakfast', 48);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (526, 'Audio', 60);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (527, 'Food - Breakfast Foods', 36);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (528, 'Clothing - Footwear', 30);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (529, 'Art Supplies', 7);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (530, 'Home Improvement', 6);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (531, 'Accessories', 52);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (532, 'Kitchen', 16);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (533, 'Fitness', 26);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (534, 'Food - Confectionery', 76);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (535, 'Clothing - Tops', 84);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (536, 'Kitchen', 2);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (537, 'Outdoor', 24);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (538, 'Pets', 66);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (539, 'Food - Breakfast Foods', 5);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (540, 'Kitchen', 22);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (541, 'Food - Frozen Meals', 1);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (542, 'Food - Produce', 87);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (543, 'Outdoor', 77);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (544, 'Food - Confectionery', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (545, 'Food - Snacks', 9);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (546, 'Kitchen', 35);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (547, 'Food - Condiments', 78);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (548, 'Clothing - Accessories', 15);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (549, 'Outdoor', 95);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (550, 'Fitness', 31);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (551, 'Home', 58);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (552, 'Clothing - Outerwear', 39);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (553, 'Food - Vegetables', 62);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (554, 'Food - Breakfast', 6);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (555, 'Pets', 50);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (556, 'Food - Canned Goods', 12);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (557, 'Food - Snacks', 1);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (558, 'Clothing - Tops', 35);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (559, 'Kitchen', 53);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (560, 'Pets', 74);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (561, 'Food - Salads', 13);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (562, 'Fitness', 40);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (563, 'Food - Canned Goods', 21);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (564, 'Food - Canned Goods', 15);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (565, 'Food - Frozen Foods', 41);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (566, 'Outdoor', 6);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (567, 'Audio', 65);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (568, 'Food - Salads', 16);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (569, 'Food - Cereal', 42);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (570, 'Electronics', 92);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (571, 'Clothing - Tops', 63);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (572, 'Food - Baking', 31);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (573, 'Kitchen', 79);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (574, 'Food - Produce', 65);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (575, 'Food - Meat', 78);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (576, 'Electronics', 62);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (577, 'Kitchen', 23);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (578, 'Food - Grains', 67);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (579, 'Food - Breakfast', 8);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (580, 'Art Supplies', 91);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (581, 'Electronics', 90);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (582, 'Food - Dairy', 39);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (583, 'Food - Snacks', 63);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (584, 'Food - Meat', 93);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (585, 'Outdoor', 97);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (586, 'Home', 96);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (587, 'Beauty', 3);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (588, 'Food - Frozen Foods', 60);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (589, 'Food - Breakfast', 1);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (590, 'Clothing - Dresses', 60);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (591, 'Outdoor', 61);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (592, 'Accessories', 27);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (593, 'Food - Cereals', 5);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (594, 'Outdoor', 66);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (595, 'Pets', 25);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (596, 'Food - Bakery', 21);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (597, 'Food - Grains', 29);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (598, 'Outdoor', 97);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (599, 'Fitness', 36);
insert into SENSORS (Sensor_ID, Sensor_Type, Weight_Kg) values (600, 'Food - Baking', 90);
